### ISSUE TITLE
Package Install failed

### ISSUE THREAD

**Issue by HarleySkin** [linux-surface/linux-surface#1028]
I installed fresh KDE Neo from usb, followed guide step by step.
I'm stuck at step :

sudo apt install linux-image-surface linux-headers-surface iptsd libwacom-surface

Terminal report:
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
linux-headers-surface : Depends: linux-headers-6.1.2-surface (= 6.1.2-surface-1) but it is not going to be installed
linux-image-surface : Depends: linux-image-6.1.2-surface (= 6.1.2-surface-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

Hardware: Surface Go 
64 GB
4 GiG Ram

**Comment by qzed** [comment]
During the latest build for Debian/Ubuntu, the package revision of the kernel package got somehow bumped up by one. So the meta-packages which should pull in the packages were built for `6.1.2-surface-1` but the kernel packages were built for `6.1.2-surface-2`. Since the meta-package is looking for a kernel with version `6.1.2-surface-1`, which doesn't exist, it breaks.

I've hopefully fixed the issue now. New packages are building and should be available in a couple of hours.

**Comment by qzed** [comment]
The repo now contains `6.1.2-surface-3` kernel packages which should fix the issue.

**Comment by qzed** [comment]
I'm closing this as the issue should be fixed. Let me know if there are still problems.
