### ISSUE TITLE
`linux-surface-secureboot-mok` EFI variable unsupported by default 

### ISSUE THREAD

**Issue by L1ghtmann** [linux-surface/linux-surface#1034]
First of all, thank you so much for maintaining this epic project! I am currently working on a minimal debian-based system to run on a bootable usb (its sole purpose it to run an executable).

It was originally based on Alpine Linux, but I recently got it ported over to a Debian Bullseye rootfs and am attempting to set it up with this kernel for use with my laptop. After installing `linux-surface-secureboot-mok`, however, I'm met with an error:
```
Setting up linux-surface-secureboot-mok (20221014-1) ...

The secure-boot certificate has been installed to

    /usr/share/linux-surface-secureboot/surface.cer

It will now be automatically enrolled for you and guarded with the password

    surface

EFI variables are not supported on this system
dpkg: error processing package linux-surface-secureboot-mok (--configure):
 installed linux-surface-secureboot-mok package post-installation script subprocess returned error exit status 1
```
After doing some searching, I've found that this is because `efivarfs` is not loaded. I'm not too familiar with kernel modules, but I was wondering if this could be resolved in a preinst script? 

Thank you in advance for your time and consideration.

### Environment

- Hardware model: Surface Laptop 3 (Intel)
- Kernel version: v6.1.3
- Distribution: Debian

**Comment by StollD** [comment]
systemd will automatically mount efivarfs, are you maybe using a different init system (e.g. sysv-init)? In that case you would need to mount it manually, or add an entry to /etc/fstab.

This is how it is mounted on my system (Fedora): 
```
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
```
Checking for efivarfs and mounting it inside the package seems reasonable to me for sysv support, but I am also not sure if I like it, because the package is already a big hack. @qzed what do you think?

**Comment by L1ghtmann** [comment]
Oop, yeah, I'm using sysvinit as that's what was used and configured in the Alpine build. And gotcha, thanks!

I'll look into switching over to systemd at some point as Debian has been using it for a while now.

**Comment by qzed** [comment]
> Checking for efivarfs and mounting it inside the package seems reasonable to me for sysv support, but I am also not sure if I like it, because the package is already a big hack. @qzed what do you think?

I guess we can do that. We're already running the mokutil commands, so we might as well run that too.

**Comment by qzed** [comment]
Okay, so I decided against mounting `efivarfs`. Mostly because it could be seen as an unexpected action and I'm not sure whether some people might want to keep `efivarfs` unmounted. Instead, I opted for a check that makes sure `efivarfs` has been mounted and issues a warning telling you to manually enroll/remove the key if not.

**Comment by L1ghtmann** [comment]
@qzed Sounds good. Appreciate your time!
