### ISSUE TITLE
Question, which is less problematic SP9 or SP8?

### ISSUE THREAD

**Issue by vbauerster** [linux-surface/linux-surface#1096]
First of all sorry for such personal question.

I never had Surface Pro before and would like to try one. I consider either SP8 or SP9 but have some dilemma which one is better for linux use. After reading wiki pages and searching for issues I came to conclusion that SP9 is more problematic than SP8. Is my conclusion right?

From what I understood:

SP9 has [screen flickering](https://github.com/linux-surface/linux-surface/wiki/Surface-Pro-9#screen-flickering) issue, while SP8 not.
SP9 has power off issue see #1058, while SP8 not.
SP9 has some ACPI error spam in dmesg see #1082, while SP8 not.
SP9 is affected by [Intel-12th-Generation-Devices-Issues](https://github.com/linux-surface/linux-surface/wiki/Intel-12th-Generation-Devices-Issues), while SP8 obviously not.

Is it worth purchasing SP9 or better go with SP8? I want less problematic devise with regards to linux.
Is any of aforementioned issues considered to be not fixable at all?

Thanks in advance, I appreciate any recommendation.

**Comment by ax0** [comment]
I haven't tried the SP8, but I've had an SP9 for a couple of weeks now. So far, I am pretty happy with the Linux experience. To address some of your points:

> SP9 has [screen flickering](https://github.com/linux-surface/linux-surface/wiki/Surface-Pro-9#screen-flickering) issue, while SP8 not.

Out of the box, yes, but the fix works.

> SP9 has power off issue see https://github.com/linux-surface/linux-surface/issues/1058, while SP8 not.

This has been fixed as well. If the power off procedure does not stall (something I've experienced on different machines), then it works. Suspend and hibernation work, but there is the audio ticking bug in the case of hibernation.

> Is it worth purchasing SP9 or better go with SP8? I want less problematic devise with regards to linux.

I haven't had much trouble with my SP9 since installing the linux-surface kernel. Everything works except for the cameras, though it is only a matter of time before they work (see #1064). Stylus and touch input work reliably. Only once have I had to manually (re)start iptsd to get stylus input working, but otherwise it works very well. I'd say it's worth it.

I hope that helps.

**Comment by vbauerster** [comment]
@ax0 May I ask you if you can utilize 120hz? Does instruction listed for [SP8](https://github.com/linux-surface/linux-surface/wiki/Surface-Pro-8#enable-120hz-and-solve-screen-flickering) apply?

**Comment by peter-marshall5** [comment]
I can confirm that 120hz works with no additional steps on my SP9.

**Comment by Nitramakloh** [comment]
@ax0 What's about ambient sensor (auto screen brightness) and screen rotation?

**Comment by peter-marshall5** [comment]
Screen rotation works perfectly by default on KDE Plasma, and probably works on Gnome and others as well.

The ambient light sensor shows up as an iio node in sysfs and seems to be reporting values correctly, but you will probably need something like [Clight](https://github.com/FedeDP/Clight) to make it control the screen brightness.

**Comment by vbauerster** [comment]
Thanks all!
I'll pick up SP8 because in my use case presence of physical audio jack is indispensable.

**Comment by BloodyIron** [comment]
For me, screen rotation and ambient sensor works on Ubuntu 22.04 (Gnome) with the surface linux kernel via the repos outlined in the installation section of this github repo. And while the display was by default set to 60hz, it was zero extra effort to switch to 120hz beyond just going to display settings and changing it to 120hz.

I have had some power/cpu weirdness after resuming from an overnight suspend, and I'm not sure how to explain that. Plus the cameras do not (yet) work.

However I plan to keep on with this ;)
