### ISSUE TITLE
Go 3: Battery stays at 100% and then drops to 94%

### ISSUE THREAD

**Issue by PhilDevProg** [linux-surface/linux-surface#1112]
[Description of the bug or feature]
When the battery is at 100%, it stays there until it reaches 94%. Only at that point the percentage gets updated. 95/96/97/98/99% does get display while charging though.

### Environment

- Hardware model: Surface Go 3 i3
- Kernel version: 6.2.8-1.surface.fc37.x86_64
- Distribution:  Fedora 37

dmesg output: 
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/11122795/dmesg.txt)

**Comment by qzed** [comment]
There's probably nothing we can do about this. The battery on the Go 3 is a standard ACPI device and values reported by it come directly from firmware.

**Comment by WolfWings** [comment]
Yeah that's a bug in whatever battery monitor app your windowing environment is using. Some of them sleep for very extended time periods on the span of a few minutes when they detect the battery at 100% to avoid causing excess battery drain.

Compare the output to this script, see if there's a big delay before the battery status updates?

`cd /sys/class/power_supply/BAT*`
`while true; do echo $[$(cat charge_now)00/$(cat charge_full)]; sleep 1; done`

**Comment by qzed** [comment]
I've seen a similar thing happen on my SB2 and I'm fairly sure it's just how the battery controller reports things. It seems that it doesn't update values frequently when it's "full", or maybe even rounds that up.

I can't really speculate why, but one reason might be that the "charge full" capacity is dynamic and can change with wear. So my guess is that this could also have been done to avoid displaying e.g. 99% when the battery is actually fully charged but the capacity has slightly degraded and the full charge cap has not been updated.

As I've said before: Since this does come from the controller, we don't have a good (if any) way to "fix" this. Also I would say that this is a fairly minor issue, so I wouldn't spend too much time investigating why the controller does this. But feel free to poke at the `charge_now`, `charge_full` and `charge_full_design` entries and see if you can make some sense of those.

**Comment by PhilDevProg** [comment]
> But feel free to poke at the `charge_now`, `charge_full` and `charge_full_design` entries (maybe separately?) and see if you can make some sense of those.


The energie_full_design of my Go 3 is 26,81 Wh/3500000 while the battery_full is 26,3044 Wh/3434000 at the moment so the current capacity of my battery is 98,1144%. But I also experienced that the battery_full was at 25,XY Wh making the capacity ~95% which shouldn't happen, right? Could this be related to the power drop issue?

**Comment by qzed** [comment]
I really know too little about how battery controllers are designed to confidently answer this. All I know is that ACPI reports a "Last Full Charge Capacity" and a "Design Capacity". For the first, specifically, it states:

> Predicted battery capacity when fully charged. The Last Full Charge Capacity value is expressed as power (mWh) or current (mAh) depending on the Power Unit value.

To me this sounds like the controller has a lot of freedom "choosing" that value. So I guess it's entirely possible that this can fluctuate somewhat.

**Comment by PhilDevProg** [comment]
I tried charging my device to 98% and then unplugged it and it showed the other numbers (97/96/95) so I guess this only happens when it's fully charged.

**Comment by ECO1AI** [comment]
> I tried charging my device to 98% and then unplugged it and it showed the other numbers (97/96/95) so I guess this only happens when it's fully charged.

what is your battery health ?

less than 90%?

**Comment by PhilDevProg** [comment]
> > I tried charging my device to 98% and then unplugged it and it showed the other numbers (97/96/95) so I guess this only happens when it's fully charged.
> 
> what is your battery health ?
> 
> less than 90%?

It's ~97-98%

**Comment by ECO1AI** [comment]
> When the battery is at 100%, it stays there until it reaches 94%.

does this happen in windows or only linux?

it seams hardware retailed ;
when fully charged, the battery wants to discharge to reach a comfortable level (94%) and the first several 0.something volt tend to quickly go (discharge). 
this is because voltage is not linearly probational to the remaining capacity, and manufacturer depends on voltage to sens the capacity and apply equation to make it more accurate.

as long as the kernel or the OS sees the voltage and other info about the battery, it should output the same output.

my battery is at 85% health (SP4) and it behaves the same as you.

**Comment by PhilDevProg** [comment]
> > When the battery is at 100%, it stays there until it reaches 94%.
> 
> does this happen in windows or only linux?

I never used Windows on this Surface so I can't check that.

> it seams hardware retailed ;
> when fully charged, the battery wants to discharge to reach a comfortable level (94%) and the first several 0.something volt tend to quickly go (discharge). 
> this is because voltage is not linearly probational to the remaining capacity, and manufacturer depends on voltage to sens the capacity and apply equation to make it more accurate.

Ah, okay.

> as long as the kernel or the OS sees the voltage and other info about the battery, it should output the same output.
> 
> my battery is at 85% health (SP4) and it behaves the same as you.
