### ISSUE TITLE
Fedora DNF Transaction Test Error

### ISSUE THREAD

**Issue by k9withabone** [linux-surface/linux-surface#1170]
When attempting to upgrade to kernel 6.3.7-1.surface.fc38 on Fedora 38, the DNF transaction test failed with the following message:

```
Error: Transaction test error:
  file /usr/bin/linux-surface-default-kernel.sh from install of kernel-surface-core-6.3.7-1.surface.fc38.x86_64 conflicts with file from package kernel-surface-core-6.3.6-2.surface.fc38.x86_64
```

### Environment

- Hardware model: Surface Pro 7
- Kernel version:
    - current: 6.3.6-2.surface.fc38.x86_64
    - trying to upgrade to: 6.3.7-1.surface.fc38.x86_64
- Distribution: Fedora 38 Workstation KDE Spin

**Comment by lucapxl** [comment]
I have the same issue:

**Environment**

- Hardware model: Surface Pro 5
- Kernel version:
- current: 6.3.6-2.surface.fc38.x86_64
- trying to upgrade to: 6.3.7-1.surface.fc38.x86_64
- Distribution: Fedora 38 Workstation

**Comment by burg1ollo866** [comment]
+1

Environment

    Hardware model: Surface Laptop Studio
    Kernel version:
        current: 6.3.6-2.surface.fc38.x86_64
        trying to upgrade to: 6.3.7-1.surface.fc38.x86_64
    Distribution: Fedora 38 Workstation

**Comment by Megamemnon** [comment]
Me too!

- Hardware model: Surface Laptop 3
- Kernel version:
-     current: 6.3.6-2.surface.fc38.x86_64
-     trying to upgrade to: 6.3.7-1.surface.fc38.x86_64
- Distribution: Fedora 38 Workstation

**Comment by qzed** [comment]
We're aware of the problem and are currently working on a fix (or rather @StollD is).

Roughly: We decided to a) restructure the kernels to allow for parallel installation and b) move contrib/fedora-default-kernel into the kernel package. It turns out that that works as long as you don't make any changes to the contrib/fedora-default-kernel files, which is why we didn't spot this in testing. As soon as you do, there's a conflict, which is what happened now.

We will therefore likely move those files to a separate package.

**Comment by Nexxkinn** [comment]
You can skip current kernel update in the meantime

```sudo dnf update --exclude="kernel-surface*"```

**Comment by qzed** [comment]
This should be fixed now with the latest update. Unfortunately, it does require a bit of manual intervention to sort out package conflicts. In particular, you need to update via
```
sudo dnf update --setopt=protect_running_kernel=False --best --allowerasing
```
See also #1159.

**Comment by k9withabone** [comment]
Can confirm that this issue seems to been resolved with the last few kernel updates. Closing the issue.
