### ISSUE TITLE
How can I boot with the gpu turned on

### ISSUE THREAD

**Issue by rodhuega** [linux-surface/linux-surface#118]
### Environment

- Hardware model: Surface Book 2 13"
- Kernel version: 5.5.8-surface
- Distribution: Ubuntu 19.10

I want to boot with the gpu turned on, so I dont want to log in, use sudo surface dgpu set on, log out of gnome and then login again. 
The reason is that with the lastest kernels and nvidia drivers we can use the feature nvidia-ondemand that you can use the gpu as if you used with bumblebee but in an official way.
For example, if you run> `glxgears` from terminal and look at nvidia-smi you will see that nothing is running at nvidia gpu, but if we use: `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only" __GL_SHOW_GRAPHICS_OSD=1 glxgears
` and look at nvidia-smi you will see that it is using the nvidia gpu.

This is not working if you start with surface dgpu set off, but if I set dgpu to on and logout and the log in. I get this working.
So, what i have to change in my OS?

**Comment by qzed** [comment]
First of all thanks for making me aware of the new on-demand feature. Have you checked how this behaves in regards to power-draw? The behavior I've previously observed is that the dGPU gets warm and draws some amount of power regardless of usage if turned on. It would be nice if that's been fixed with that feature and driver update. I don't have the time to play around with this at the moment but I'll definitely check it out. All in all you might want to have a look at that in case you observe a drop in battery life.

_To your actual question:_  The default power-state is controlled via module parameters. There's some info about this on the SAM repo: https://github.com/linux-surface/surface-aggregator-module#controlling-the-dgpu-power-state. In essence:
1. Create a new `.conf` file in `/etc/modprobe.d/`, e.g. `/etc/modprobe.d/dgpu.conf`
2. In the file, add the line `options surface_sam_hps dgpu_power_init=1` (if you use the SAM module via the kernel, or `options surface_sam dgpu_power_init=1` if you've manually installed the SAM module from the repo).
3. Reboot.

Of course you could also write a systemd service to just run `surface dgpu set on` (or any kind of script that checks that based on some condition) before the graphical target if you want to have more control.

**Comment by rodhuega** [comment]
Thank you, In my case, the temperature is around 35C. About the battery life, I don't know, I was playing with the ubuntu installation since yesterday. I think this feature will be easier to use in gnome 3.36 delivered with ubuntu 20.04 with the support of switcheero for nvidia cards.  When I have more use with battery I will tell you my results.
PD: If  you boot in the way I say, you can turn the nvidia card off  with `surface dgpu set off` but then when you turn it on, nvidia-smi and other modules of nvidia won't work. May be there is a way to achieve this and have a real power saving nvidia offloading, but i don't know how. I know that nvidia turing cards could do it out of the box in linux with the latest drivers.

**Comment by qzed** [comment]
35C seems to be a bit warmer than I'd have hoped, might be that that goes down over time if the dGPU enters some power-save mode.

Another problem with having the dGPU on by default was/(is?) that Gnome seems to "claim" the device if it's started while the dGPU is on, so turning it off (without shutting down the Gnome session beforehand) will cause issues. In general you should always make sure to unload the nivida drivers before turning the dGPU off, so that you can be sure the device isn't being used any more. In case of the Gnome issue, for example, I couldn't unload the drivers (so turning it off with the drivers loaded and in-use is a good indication that something's going to break).

**Comment by rodhuega** [comment]
I have been using my surface book 2 with gpu on at start up and the prime-select on demand and i think is unstable. For example when you power off the computer a lot of times it doesn't power off. Another times you have problems with suspend. At the end I move to gpu off at start up and if i need to do some cuda stuff i will turn on gpu and i dont need to log out to execute or compile with nvcc. If i need to do some 3d stuff then I log out. 
Thanks for the help.

**Comment by qzed** [comment]
Thanks for reporting back! I had hoped the situation would have improved a bit. Looks like dual GPU setups still need some work and unfortunately the SB2 is a bit special due to it being detachable.
