### ISSUE TITLE
[Enhancement] to make writing more natural

### ISSUE THREAD

**Issue by riccardoregina** [linux-surface/linux-surface#1182]
[Description of the bug or feature]

Hi, it's clear that Microsoft shifted the input of the surface pen a little bit: this is a nice detail that makes writing on the screen feel more natural. At this moment, the coordinates of the stroke are too precise: this is due to the width of the glass panel.
This would be a really nice and appreciated feature.

### Environment

- Hardware model: Surface Pro 8
- Kernel version: Linux SurfacePro8 6.3.7-surface (hashtag)1 SMP PREEMPT_DYNAMIC Wed Jun 14 12:57:39 UTC 2023 x86_64 GNU/Linux
- Distribution: Debian 12
- Stylus: Surface Slim Pen 2

**Comment by StollD** [comment]
Do you mean that the cursor is not at the tip of your pen, but slightly shifted towards you? If so, correcting this offset is already possible, but it is not enabled by default because it requires the distance between the tip of your pen and the transmitter. I dont know if this is the same for all pen models, and older devices already do this internally to some degree.

https://github.com/linux-surface/iptsd/blob/master/etc/iptsd.conf#L137-L143

You can enable it by putting this into a `.conf` file in `/etc/iptsd.d` and then restarting iptsd with `systemctl restart $(iptsd-find-service)`

```ini
[Stylus]
TipDistance = 0.0
```

Then increase the value of `TipDistance` until the cursor and the tip of the pen align.

**Comment by riccardoregina** [comment]
That's exactly what I meant. Thank you for the instructions.
I'm going to tinker a little bit with the parameters in order to find a good setup for the surface slim pen 2 and maybe share it.
Moreover, since the software detects the hardware, wouldn't it be pleasant to get these "fixes" out of the box?

**Comment by StollD** [comment]
It can only identify the digitizer, I don't know how to identify the pen. And like I said, I dont know if a single value can work for all pens (including third party ones).

And since I dont own a device where this correction is neccessary (because it is done by the hardware already), I am a bit reluctant to just put default values for these options.

**Comment by riccardoregina** [comment]
Ok, I was ignoring the existence of third part pens...
Thank you
