### ISSUE TITLE
Surface Pen incorrect screen coordinates mapping on Wayland

### ISSUE THREAD

**Issue by jdperos** [linux-surface/linux-surface#1237]
Hello,

After going through the whole installation process on Ubuntu, I am encountering an issue when using my Surface Pen on Wayland. Bear with me for this description... it appears that the cursor coordinate values are doubled of the pen input values. So if the top left of the screen is (0,0), and the bottom right of the screen were (100,100) for instance - the pen at (0,0) would move the cursor to (0,0), but if the pen is at (50,50), the center of the screen, the cursor is at (100,100), the bottom right of the screen. This means that the further away from the top left of the screen my pen input is, the more offset my cursor is from my pen. Obviously this makes the pen unusable, if the cursor is not consistently under the pen input.

Here is a sketch to attempt to clarify:

![SurfacePen](https://github.com/linux-surface/linux-surface/assets/14932091/bb64a347-e151-48cf-9373-7970cde90342)

Some notes:
- Touch input works fine. Exactly as expected, with the selection being right under the fingertips
- The pen works as expected in Xorg, as opposed to Wayland - however, then I lose touch gesture support which I need for my workflow
- Display scaling is irrelevant. Whether the display is 100% or 200% scaled, the issue persists
- I have run the Wacom tablet calibration, which only seems relevant to touch, not pen

### Environment

- Hardware model: Surface Book 2
- Kernel version: Linux Surface-Book-2-Ubuntu 6.4.7-surface #3 SMP PREEMPT_DYNAMIC Tue Aug  1 21:23:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 22.04
- Desktop session type: Wayland

**Comment by StollD** [comment]
I remember fixing a very similar issue on GNOME, just that it was the opposite issue. Drawing in the bottom corner drew in the center of the screen.

> I have run the Wacom tablet calibration, which only seems relevant to touch, not pen

Was that after you noticed that it was broken? Because I can remember some reports that the calibration doesn't work correctly and just breaks the coordinate mapping.

Generally GNOME on Ubuntu 22.04 seems to have some issues recently. See also https://github.com/linux-surface/linux-surface/issues/1199.

The chance is pretty high that this is not an issue of our touchscreen drivers and instead an issue in GNOME itself. To verify this, you need to run these commands:

```
$ sudo systemctl stop $(iptsd-find-service)
$ sudo iptsd-show $(iptsd-find-hidraw)
```

This will open a fullscreen window that visualizes the touch inputs. Please check if the position of the stylus aligns with the position on screen there.

Alternatively, since this is a new install, is there a chance you could test this on KDE (Kubuntu)?

**Comment by jdperos** [comment]
> Was that after you noticed that it was broken? Because I can remember some reports that the calibration doesn't work correctly and just breaks the coordinate mapping.

I actually noticed that it was broken after I ran the calibration. But I don't have a clear memory of if I used the pen before running calibration.

To test this, is there a way to wipe those settings, or reinstall back to a previous state before running that?

After running these commands:
```
$ sudo systemctl stop $(iptsd-find-service)
$ sudo iptsd-show $(iptsd-find-hidraw)
```
I am brought to a blank screen, and the draw cursor aligns perfectly with the pen.

> Alternatively, since this is a new install, is there a chance you could test this on KDE (Kubuntu)?

It'll be a little difficult with how I'm currently using this laptop, so if doing something in the vein of just wiping and reinstalling the surface settings in this desktop can answer questions, I'd do that first.

**Comment by StollD** [comment]
> To test this, is there a way to wipe those settings, or reinstall back to a previous state before running that?

This post contains information on how to reset it. I can't test it though, as I don't run GNOME: https://bbs.archlinux.org/viewtopic.php?id=271284

There is also an alternative workaround here that you can try: https://github.com/linux-surface/linux-surface/issues/288

**Comment by jdperos** [comment]
Absolutely great. running the steps on post 3 solved it. Guess it's a gnome issue, not a Linux Surface issue!
