### ISSUE TITLE
kernel & dkms errors on fresh Debian 12 install

### ISSUE THREAD

**Issue by lifewater** [linux-surface/linux-surface#1296]
I'm experiencing an issue installing the linux-surface kernel, getting several errors from dkms as well as dpkg.  This is a fresh install of debian with only `linux-headers-amd64 and nvidia-kernel-dkms installed` prior to running the commands provided from linux-surface kernel instructions.  These packages were required to properly install nvidia-kernel-dkms (i think?).  Was following this: https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_12_.22Bookworm.22

### Environment

- Hardware model: Surface Book 2
- Kernel version: Linux 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux-->
- Distribution: Debian 12

<details>
<summary>surface kernel installation output</summary>
https://pastebin.com/9pmw0U8b

<summary>nvidia make log output</summary>
https://pastebin.com/m2nKV29G

<summary>`dmesg` output</summary>
https://pastebin.com/GadWR9xR

</details>

**Comment by qzed** [comment]
Unfortunately, that's a something we can't easily fix. The DKMS nvidia packages shipped with your distro are designed for an older kernel. So occasionally (as happened here), the shipped DKMS package and our kernel are incompatible. You could try to look for a newer package, but that might involve some manual work.

However, since you are running a SB2, you might also be pretty happy with the v6.1 kernel shipped by your Debian version. The things you'd be missing out are touch and cameras, but apart from that, everything should work.

**Comment by lifewater** [comment]
Hmm ok, it was worth a shot.  I will go back to Ubuntu for the time being, as everything is working smoothly on that
