### ISSUE TITLE
Secure Boot and Grub GFX Mode

### ISSUE THREAD

**Issue by n0valis** [linux-surface/linux-surface#1320]
Grub Menu appears very small with original confguration. Therefore GRUB_GFXMODE has to be set. But causes issues.
With Secure boot on I cannot read the Grub Menu anyway. 

fyi: I tried to install the key with linux-surface-secureboot-mok but the MokManager after reboot never appeared.
**However I have no issues to boot into LMDE with secure boot on.**

Instead the Grub Menu ignores the GRUB_GFXMODE setting is ignored if I switch on secure boot in BIOS.
If I switch secure boot of,  GRUB_GFXMODE setting works as intended.
The Grub Menu without settings for GRUB_GFXMODE are immensly smal, almost unreadable, so that why it is kind of neccessary.

Do you have any idea how the secure boot setting affects the GRUB_GFXMODE setting. 
I placed the setting in /ezc/default/grub and did install-grub.
After that it was written to /boot/grub.cfg as expected. And as I said: worked as long as I had secure boot turned off.

It is now "toggable" Secure boot on -> mini grub menu, secure boot off -> normal grub menu

### Environment
- Hardware model: Surface Pro 9
- Kernel version: 6.6.5
- Distribution: LMDE6

**Comment by StollD** [comment]
When secureboot is enabled, the fonts that are loaded for graphical output in GRUB have to be signed. By default they aren't.

Because it can't load the font file it falls back to writing text into the UEFI framebuffer which is 3000x2000 pixels or something like that.

Because of how GRUB works, signing modules or fonts requires embedded a GPG key into the actual executable, which in turn forces you to sign the executable yourself too. If you want to go down that route, this might help: https://bbs.archlinux.org/viewtopic.php?pid=2103579#p2103579

**Comment by n0valis** [comment]
All right. Rather complicated. Thank you for pointing that out.
