### ISSUE TITLE
Surface Laptop Studio acpi_listen not detecting insertion/removal of AC adapter

### ISSUE THREAD

**Issue by BlueCreeper512** [linux-surface/linux-surface#1326]
When removing or inserting the AC adapter, no power/AC adapter events are logged in the terminal when running acpi_listen, however the battery driver itself does appear to be working as the battery icon does show up in the top menu bar and it seems to be able to tell that the AC power has been removed. Also only power events seem to not show up in acpi_listen as adjusting volume/brightness and pressing the power button all get logged.

As far as I can tell this issue seems to be the cause for another issue where the PowerMizer Power Source readout in the NVIDIA X Server Settings displays "Error" when waking from the D3cold state causing the 3050 Ti to always be stuck with a 10W power limit and the lowest clock speeds even when a graphically intensive load is applied.

- Hardware model: Surface Laptop Studio
- Kernel version: ```Linux pop-os 6.6.6-surface-1 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 22:43:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```
- Distribution: Pop!_OS 22.04 LTS

dmesg output: https://pastebin.com/vxaE2xMe

**Comment by qzed** [comment]
That is the expected behavior. `acpi_listen` only listens to ACPI events, so it will only work as long as the battery is implemented via ACPI (and thus sends ACPI events). On newer Surface devices, that is not the case and they instead use their own interface and driver. So those devices cannot send ACPI battery events.

I suggest you instead try `upower` (e.g., via `upower -m`), which will actually listen to battery events. Note that the kernel sends battery events regardless of how the battery is implemented. This is how the different desktop envs implement battery status information.

**Comment by BlueCreeper512** [comment]
> Note that the kernel sends battery events regardless of how the battery is implemented. This is how the different desktop envs implement battery status information.

So that means that the NVIDIA driver/PowerMizer should be detecting the AC adapter insertion/removal regardless of whether the battery is implemented via ACPI or in this case, its own interface and driver correct?

**Comment by qzed** [comment]
I would hope so. Ideally, it would just use either the kernel's /sys/class/power_supply interface directly or use upower. But I'm really not sure how that program works. In the past, I think some programs did just listen to the ACPI events (but I think those were mostly more on the side of custom scripts for stuff like xmonad or some other of these heavily customizable desktop managers though).

**Comment by BlueCreeper512** [comment]
Okay, thanks for the help. I guess I'll have to ask this one over on the NVIDIA forums.
