### ISSUE TITLE
Plans to add a binary release for LTS kernel 5.4?

### ISSUE THREAD

**Issue by jerkstorecaller** [linux-surface/linux-surface#135]
I was looking at the Debian packages and noticed you have packages for kernel 4.19 (previous LTS, though still supported), and then 5.5. But no 5.4.

The latest kernel LTS is 5.4 (as of December 2019). It's what will be used in Ubuntu 20.04 LTS, coming out late next month. Ubuntu and its derivatives are ~~arguably~~ the most popular home user distros.

I think it would be a good idea to support the new kernel LTS for this reason.

**Comment by StollD** [comment]
As of 5.4+, the kernel doesn't support the old IPTS touchscreen driver anymore. We are working on a new driver, but it will take some time to get feature equality to the old one. 4.19 is the latest kernel that still supports the old driver, and still gets updates to we chose to support that instead of 5.4.

And to be honest, adding another kernel package to the repo seems like a mess, and takes time away from actual development. So I don't think a third package for 5.4 makes much sense.

**Comment by qzed** [comment]
@kachapman There shouldn't be any notable differences. If you need custom kernel modules (e.g. via dkms) there might be issues if the distro expects a newer kernel, but I doubt that (those should normally be backwards compatible, I hope).

**Comment by kachapman** [comment]
> @kachapman There shouldn't be any notable differences. If you need custom kernel modules (e.g. via dkms) there might be issues if the distro expects a newer kernel, but I doubt that (those should normally be backwards compatible, I hope).
So how involved is the process of downgrading?

**Comment by qzed** [comment]
@kachapman It's not really downgrading as you can install multiple kernels in parallel. Just install the lts kernel (`linux-headers-surface-lts` and `linux-image-surface-lts` packages for Debian/Ubuntu). After that you may need to edit your bootloader config to automatically boot into the lts kernel (you can also manually select the kernel in the bootloader).

**Comment by archseer** [comment]
Closing since this issue is old and we do offer LTS releases now.
