### ISSUE TITLE
Timed Out Waiting for DTX on Bootup

### ISSUE THREAD

**Issue by manuth** [linux-surface/linux-surface#1420]
Sometimes (avg. every 2 out of 3 times), ArchLinux gets stuck with the message "Timed out waiting for /dev/surface/dtx".

Waiting for the boot to finish (after having the step skipped by waiting for about 10mins), causes a black screen with nothing but the cursor visible.

### Environment

- Hardware model: Surface Book 2 Pro
- Kernel version: `Linux manu-surface 6.8.1-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Thu, 21 Mar 2024 10:48:58 +0000 x86_64 GNU/Linux`
- Distribution: Arch Linux

### `dmesg` output

n/a cannot boot into a graphical environment after the error occurred.

**Comment by manuth** [comment]
Do you guys know of anything I could do to prevent this from happening?
I tried adding the `dtx` module to the `initrd` with no success.

**Comment by qzed** [comment]
It looks like for some reason the `/dev/suface/dtx` device doesn't show up. This causes the 'surface-dtx-daemon' to wait for it, which ultimately causes that message.

I think this is related to #1319 and #1271, where the SAM driver fails to load for some reason. Due to that missing, the DTX driver will also not load. Meaning the device won't be there and you get that message.

A temporary workaround could be to `systemctl disable surface-dtx-daemon.service`, but that means that the SB2 detachment will be slower.

**Comment by manuth** [comment]
Awesome!
Thank you so much for helping me out once more 😄 
Should this issue be closed, considering that there are other issues describing the problem more accurately?

**Comment by qzed** [comment]
>  Should this issue be closed, considering that there are other issues describing the problem more accurately?

Yeah, that's probably a good idea. Also see https://github.com/linux-surface/linux-surface/issues/1319#issuecomment-2059468939 for a potential workaround.
