### ISSUE TITLE
Surface Pro 10 Supported?

### ISSUE THREAD

**Issue by tabletseeker** [linux-surface/linux-surface#1447]
Hello, I just wanted to ask if the Surface Pro 10 requires any major modifications to the kernel config or additional patches and at the same time would like to offer my assistance if I can help in any way. Regards

**Comment by westlikeslinux** [comment]
No, it has a special ARM CPU so its basically impossible to install linux no matter what unless you have the special drivers with a perfectly compatible distro.

**Comment by kwai-chang** [comment]
U can choose Intel CPU i5, i7 or ARM, main functions will work.
To my SP9 all is very good, only camera and pen.

**Comment by qzed** [comment]
I haven't seen any reports from Intel/x86 Surface Pro 10 yet, so I can't give you a 100% guarantee. But if they didn't change much, it will likely need the usual patches to enable SAM support. That should be doable fairly quickly if someone is willing to test things.

For the ARM variants, on the other hand, things will take a lot longer. People are currently working on supporting the new Qualcomm SoC for a Lenovo device that's using it, but we'd have to write a completely new device tree based on that. I haven't followed the development of that so I'm not sure what's working on that SoC right now, but even if all the major things would be working, it's still quite a lot to do. I mean I'm still working (somewhat less active right now due to daytime work) on the SPX (most things are there, but there are some hacks and workarounds that need to be fixed before I can really upstream things). And then, even if you have a device tree (DT), it will still not be a smooth installation experience because the device was intended for ACPI instead of DT, so unless you have a special installer designed for that device, you will need to do set a bunch of things up manually.
