### ISSUE TITLE
Kernel does not install

### ISSUE THREAD

**Issue by JoshAtticus** [linux-surface/linux-surface#1513]
[Description of the bug or feature]

### Environment

- Hardware model: Surface Laptop 3 (Intel) 
- Kernel version: Linux BigSurface 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux 
- Distribution: ZorinOS 17.1 Core

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

When trying to install linux surface kernel like displayed in the installation guide, the packages install however the kernel isn't added to the /boot directory and the system boots into standard kernel when the machine boots.

If it helps, I stupidly rm -rf'd the 2 surface linux kernel files when trying to fix secure boot stuff since MOK manager wouldn't boot, and now with MOK manager working the kernel will not reinstall.

**Comment by JoshAtticus** [comment]
It looks like the deb files from pkg.surfacelinux.com are completely empty, instead I downloaded the 2 largest files from GitHub releases and installed those, let me test now

**Comment by JoshAtticus** [comment]
It worked!

**Comment by qzed** [comment]
The deb packages without content and version directly in the name are meta-packages. They pull in the actual kernel package, which contains a version in the name, as dependency. This basically models what Ubuntu/Debian do for their kernel packages.

In essence, the meta-package is required so that things automatically update with the version-contained-in-name actual kernel package, but the actual content is only present in the latter.
