### ISSUE TITLE
6.12 - Rebase request 

### ISSUE THREAD

**Issue by LionHeartP** [linux-surface/linux-surface#1621]
Once again I'm here to ask you guys for a kernel 6.12 rebase of the patches.

**Comment by derkrasseleo** [comment]
And please also merge the ipu6 patch

**Comment by qzed** [comment]
I will likely be quite busy until mid-December and I might not be able to update things here before that, sorry. I'll do both as soon as I find some free time.

**Comment by brettwilcox** [comment]
@qzed Thank you very much for maintaining this repo! I work for American Airlines as a cybersecurity engineer and daily drive this kernel on a Surface Book 2. If you would like help maintaining releases, let me know and I would be willing to assist.

Is there any documentation on how to update from upstream?

**Comment by ReillyBrogan** [comment]
> @qzed Thank you very much for maintaining this repo! I work for American Airlines as a cybersecurity engineer and daily drive this kernel on a Surface Book 2. If you would like help maintaining releases, let me know and I would be willing to assist.

If you're serious on this you'd probably be best off joining the Surface development Matrix. The other developers seem to lurk there. 

> Is there any documentation on how to update from upstream?

Have you ever rebased a large kernel patchset before? It's not very easy if you've never done it before, and it at minimum requires enough understanding of C to figure out what to do with inevitable merge conflicts. It also requires a fair bit of git experience as rebasing is not exactly intuitive.

Basically, the workflow would look like this:
1. Clone the surface kernel source: https://github.com/linux-surface/kernel
2. Add gregkh's stable repo as an additional remote, and fetch the tags from it
3. Checkout the `v6.11-surface` branch and then create a new branch `v6.12-devel` (or something similar) from it
4. Do an interactive rebase on the latest 6.12 tag (`6.12.3` at the time of writing this). Drop all of the stable commits (you'll see what I mean but it'll be all the commits that git sees that are in the 6.11 stable branch that are part of the stable kernel itself that are not in the 6.12 kernel). Continue the rebase
5. Go through each commit and fix it as needed. You should be able to build the kernel after every commit.
6. Test the final series to ensure that everything is functional.
7. Push your branch somewhere so that others can take a look.

**Comment by qzed** [comment]
@brettwilcox Thanks for the offer. That actually sounds great! I'll try to update things this evening but I'll probably come back to your offer soon, if you're still interested after knowing the details :) 

As for how things are updated: Generally everything runs via our kernel repo. @ReillyBrogan basically described the process pretty well. Although I don't rebase from the stable branch directly because that usually diverts from the actual development upstream branch and use `git cherry-pick` instead to apply our patches. So for v6.12 it should be something like `git checkout v6.12.x`, `git cherry-pick <hashes-range from v6.11-surface>`. Occasionally it can't apply the patches cleanly, so they will have to be fixed up interactively.

Apart from that we have a custom `Patchset: <...>` tag to group patches together in one file. I wrote a git extension (https://github.com/qzed/git-tools/blob/master/git-format-patchsets) so I can just call `git format-patchsets <base commit hash>` to generate the patch files here in this repo.

And then lastly in this repo (after some testing of course), update all the package data. Arch Linux is fairly standard (with a PKGBUILD where you just need to update the version and hashes; plus each major release the config from the official Arch config), Debian and Fedora are a bit more custom but usually it's basically also just updating a version field (unless something changed which causes some of the build-patches to fail applying, meaning they have to be updated as well).

So all in all, you should have some experience of C, ideally also about linux kernel development to fix-up the occasional patch, and basic experience with packaging stuff.

**Comment by brettwilcox** [comment]
@ReillyBrogan @qzed Awesome! I definitely think I can help. If you send me an email the next time you compile to a new version, I would be happy to setup a screen share meeting so I can learn the process. I understand you are in Germany, so I'm happy to accommodate whatever time works best for you.

firstname.lastname@aa.com
brett@scorpion.io

**Comment by LionHeartP** [comment]
Thanks for the rebase.
