### ISSUE TITLE
Touchscreen isn't smooth

### ISSUE THREAD

**Issue by danielzgtg** [linux-surface/linux-surface#171]
Every time I scroll with the touchscreen, it just feels a bit ... weird. The cursor isn't updated frequently enough. I can almost start to see the individual frames. Scrolling with the touchscreen in Linux makes me anxious while scrolling in Windows is just relaxing.

I would expect this after the removal of GuC and any GPU accelerated touchscreen processing. The forward to userspace thing might also fix this.

It is the same uncomfortable experience I get when a 60 FPS game drops to 15 FPS. This is especially pronounced right after when switching to and from Windows. I also notice it when switching to and from the touchpad. When I let go of a page, things look right again while the page continues scrolling for a bit, making it most likely the touchscreen driver's fault.

Implementing GuC/GPU/userspace would be the best way to fix this. I'm also guessing it's not a good idea to increase the polling frequency.

However, there could be a workaround that can be implemented in the meantime. Inertia can be added. While the finger is on the screen, the kernel would send extrapolated touch events to userspace in between touch events analyzed from hardware. This would cause scrolling to be smooth again.

### Environment

- Hardware model: `Surface Pro 7 i7 512GB`
- Kernel version: `Linux daniel-tablet1 5.6.5-surface #2 SMP Mon Apr 20 16:23:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: `Ubuntu 20.04 Desktop`

**Comment by StollD** [comment]
There is no processing involved with the current singletouch implementation. The Intel ME provides us with raw data: one byte for if a finger is touching the screen, and four bytes for x and y. All that the driver does is forward this data into the linux input subsystem.

Some processing is required for the tilt values on the stylus, and a lot of it will be required to implement multitouch, but even if that was implemented, it wouldn't work on gen7 devices at the moment. We don't know how to get anything except singletouch data on those at the moment.

Regarding speed: Ideally you want to keep the processing in kernel space, because kernel space is faster than userspace. If you forward it to userspace you can introduce delays because the kernel has to switch between CPU isolation rings, setup things like the CPU floating point unit, and flush buffers to protect you from meltdown / spectre vulnerabilities.

However, for the touchscreen, we will most likely have to do it in userspace, since we need floating point calculations, which are not supported in kernel space, at least not without a lot of work. So going to userspace is the least bad option, not the absolutely best one.

Regarding Firefox: All that the driver can do is emit events to userspace. It does not control how those events are processed by applications and / or toolkits. For example firefox doesn't use a toolkit, so they need to implement the scrolling logic themselves, which means it won't be consistent with other apps.

Since you use Ubuntu, you probably also use X11 / X.org as your display server since thats the default. The X11 protocol is so old, that it doesn't have special support for touchscreens or styli. All these input events will be interpreted as a mouse pointer. There are ways for applications to make it work, but it sounds like this could be a reason for the issues you describe. To solve this you could switch to a wayland session (you can change the session type in the login screen), and see if the issue persists there. Wayland is a newer protocol than X11, and has proper support for different pointer devices.

I use Gnome + Wayland (granted, on Fedora not Ubuntu, but same software with different packaging), and for me the scrolling in Firefox is not too different from scrolling with the touchpad (pretty smooth).

**Comment by danielzgtg** [comment]
I just tried out Ubuntu 20.04 (it uses GNOME now) on Wayland. Firefox needed a config to get touchscreen scrolling working.

Firefox seems to have it's own smoothing. It's not as smooth as windows but scrolling feels much smoother now and I don't feel dizzy anymore. I get the same smoothness problems as in Chrome when I disable `general.smoothScroll`. I also found out that I can get the same behavior in Chrome by enabling `#smooth-scrolling`.

However, there is now a latency and a touchpad problem with Firefox's smooth scrolling. Adding inertia to the kernel driver might not be a good suggestion after all as it's the same idea. When my finger changes direction when scrolling, the webpage continues moving in the original direction for a moment (which on Windows is much more brief). For touchpad scrolling, whereas it was as good on Linux as on Windows without browser smooth scrolling, it became as bad as touchscreen scrolling on Linux with it enabled. Now it also lags behind my finger and doesn't feel as precise anymore.

At least you mentioning Firefox made me aware of a workaround that alleviated the discomfort. However, it is still not as smooth as Windows. That said, I am the kind of person to immediately notice the difference between 30 FPS and 60 FPS as well as an extra 10 ms of latency.

With regards to the solution, I now think GPU is crucial. It might be the case that Intel ME is doing the heatmap processing itself and no matter who is doing the heatmap processing, it will not be fast enough on a CPU, regardless of whether it's the main CPU or the Intel ME microprocessor. It would be really nice if Intel would reenable the GuC code in the kernel now.

**Comment by xXBeekeyXx** [comment]
I assume you are talking about scrolling in the browser. What browser are you using? Try to switch to chromium to see if the issue is still there.

**Comment by danielzgtg** [comment]
I tried Chromium, Google Chrome, and Firefox.

I wrote some code to see how fast touch events were actually being sent to the userspace:

```html
<body>
<style>
#box {width: 50vw;height: 50vh;background: #aaa;}
</style>
<div id="box">
</div>
<p id="output">Loading</p>
<script>
let fps = 0, touchX = 0, touchY = 0, mouseX = 0, mouseY = 0;
output.innerText = "Please swipe back and forth vertically in the box";

box.addEventListener("mousemove", e => {
const {offsetX, offsetY} = e;
if (offsetX != mouseX || offestY != mouseY) {
mouseX = offsetX; mouseY = offsetY;
fps += 1;
}
});

box.addEventListener("touchmove", e => {
const {clientX, clientY} = e.touches[0];
if (clientX != touchX || clientY != touchY) {
touchX = clientX; touchY = clientY;
fps += 1;
}
});

setInterval(() => {output.innerText = fps + " FPS";fps = 0;}, 1000);
</script>
</body>
```

Here are the results:

| Computer | OS | Window Manager | Browser | Touchscreen poll Hz | Touchpad poll Hz |
| --- | --- | --- | --- | --- | --- |
| Desktop | Linux |  X11 | Google Chrome | 60 | N/A |
| Surface | Linux | X11 | Firefox | 60 | 35 |
| Surface | Linux | X11 | Chromium | 60 | 35 |
| Surface | Linux | X11 | Google Chrome | 60 | 35 |
| Surface | Linux | Wayland | Firefox | 60 | 100 |
| Surface | Linux | Wayland | Chromium | 60 | 35 |
| Surface | Linux | Wayland | Google Chrome | 60 | 35 |
| Surface | Windows | Windows | Google Chrome | 60 | 60 |

As it is possible to get 100 Hz touchscreen input on Linux, I no longer think it's the kernel's problem.

I now wonder:

- What's wrong with Chrome's handling of touchscreen input on Linux?
- Is there a difference in rendering performance?

**Comment by danielzgtg** [comment]
I tested the rendering performance by turning on the browsers' FPS meters and pasting the following code into DevTools with https://en.wikipedia.org/wiki/Main_Page open:

```javascript
(function() {
let x = 0, y = 0, fps = 0;
document.onscroll = () => {if (scrollX != x || scrollY != y) {
x = scrollX; y = scrollY;
fps += 1;
}};
setInterval(() => {
console.log(fps + "FPS");
fps = 0;
}, 1000);
})();
```

Here are the results:

| Computer | OS | Window Manager | Browser | Touchpad scroll Hz | Touchpad render FPS | Touchscreen scroll Hz | Touchscreen render FPS |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Desktop | Linux | X11 | Google Chrome | 60 | 60 | N/A | N/A |
| Surface | Linux | X11 | Firefox | 60 | 60 | 35 | 40 |
| Surface | Linux | X11 | Chromium | 60 | 60 | 35 | 35 |
| Surface | Linux | X11 | Google Chrome | 60 | 60 | 35 | 35 |
| Surface | Linux | Wayland | Firefox | 60 | 60 | 35 | 40 |
| Surface | Linux | Wayland | Chromium | 40 | 50 | 35 | 40 |
| Surface | Linux | Wayland | Google Chrome | 35 | 45 | 35 | 40 |
| Surface | Windows | Windows | Google Chrome | 55 | 55 | 60 | 60 |

Switching from X11 to Wayland, I see that Chrome also has trouble with not only the touchscreen scroll events but also the touchpad scroll events. I also see that despite Firefox handling the mouse events faster, its scrolling frequency is as bad as Chrome.

Looking at the resulting FPS of Linux and Windows, there is indeed a ~25 FPS difference. When I let go of the scrolling, it goes back up to 60 FPS which I perceive as smooth. As it's capable of 60 FPS, the problem is narrowed down to input handling instead of rendering.

Something in userspace is taking too much time handling inputs.

**Comment by danielzgtg** [comment]
This issue no longer affects me. Scrolling on Chrome 85 with Linux 5.8.5-surface with iptsd is at a buttery smooth 60 FPS.
