### ISSUE TITLE
SP7 Stuck in Loading initial ramdisk with LTS 

### ISSUE THREAD

**Issue by nasiaf** [linux-surface/linux-surface#193]
Hi, 

I got a SP7 with Ubuntu 20. Everything fine with 5.6.X kernel. 
As the screentouch is not well supported by this version, i would like to use the 4.19 LTS kernel. 

But when i try to boot on this kernel, i get stuck at "Loading initial ramdisk...", and I can't understand why. 

Thanks a lot

**Comment by StollD** [comment]
The 4.19 LTS kernel is too old to have support for the Icelake CPUs / iGPUs that the SP7 uses.

Furthermore, the multitouch support on 4.19 is only for gen4-6 devices, because with gen7 IPTS (the touchscreen technology) was changed significantly. The old driver from 4.19 wouldn't work at all on your device.

**Comment by nasiaf** [comment]
Ok thx for the help
