### ISSUE TITLE
SP7: High battery drain on suspend

### ISSUE THREAD

**Issue by Crashdummyy** [linux-surface/linux-surface#198]
# Environment
```bash
- Hardware model: Surface Pro 7 ( i5 )
- Kernel version: 5.6.14-surface 
- Distribution: Ubuntu 20.04 LTS
```
# Error
Suspending the surface appears to drain the battery quite a lot: ( 3-4% hourly )

Is there something I can do to prevent this?  
The bootprocess takes about a minute so I would rather keep the device in sleep

**Comment by archseer** [comment]
Surfaces (and new-ish laptops) use S0ix ("Connected standby") instead of normal suspend. Microsoft decided that your laptop should work like a mobile phone and keep certain things running in the background. It's dumb and really easy for apps or services to wake up your device unintentionally, leading to 1~2% battery usage per hour for me. There's some docs on tuning here:
https://01.org/blogs/qwang59/2018/how-achieve-s0ix-states-linux

On some devices it's possible to get regular suspend back via dsdt table patching but it's quite possible that Microsoft removed support for it in hardware. I've been relying on hibernate (or suspend-then-hibernate)
