### ISSUE TITLE
Swap order of choices for suspend/hibernate

### ISSUE THREAD

**Issue by danielzfranklin** [linux-surface/linux-surface#21]
I also feel lightly stressed and have to read through your choices in `setup.sh` very carefully because it doesn't follow the default of making the recommended choice the default. In this case, I'm recommending that you make suspend the "yes" answer. I'd also recommend you add a notice that this change. That way people who want to use the recommended defaults can just press enter.

This is especially confusing because all the other "yes" options are the more common choices.

Would you accept a PR that makes this change?

**Comment by archseer** [comment]
The setup script is a bit dated at this point, the reason hibernate is the default over suspend is because suspend used to not work at all. At this point, both options should work, and the user should do the replacement manually (probably by changing logind.conf instead of overriding targets).

We're working on a bit of a cleanup here that also drops a bunch of outdated config files: https://github.com/linux-surface/linux-surface/compare/master...linux-surface:feature/setup-script

https://github.com/linux-surface/linux-surface/commit/5a9e26418308f038807c824cd8d47aba6321ff59

**Comment by danielzfranklin** [comment]
Great. I'll close this then. FYI, the old phrasing made it seem like suspend was your strong recommendation.
