### ISSUE TITLE
Ubuntu version compatibliity matrix

### ISSUE THREAD

**Issue by fkromer** [linux-surface/linux-surface#231]
As [Ubuntu server 20.04 LTS is based on kernel 5.4](https://ubuntu.com/blog/ubuntu-server-20-04) it should be supported. Has anyone already tried it on Ubuntu server 20.04? Probably it would be helpful to a a compatibility matrix in the wiki for Ubuntu as one of the most common distros?

- 18.04 (SP7 - battery  status - ?): https://github.com/linux-surface/linux-surface/issues/228
- 18.04 (SP7 - bluetooth - OK): https://github.com/linux-surface/linux-surface/issues/55
- ...

**Comment by qzed** [comment]
What specifically do you have in mind? A matrix of what's supported out of the box on specific Ubuntu versions? Or what's supported with the kernel provided in this repo? The latter is already available at https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features. This represents the state of the current kernels, both 5.7/latest and 4.19/LTS.

Having those features split out by Ubuntu version does not make much sense to me, as the support indicated on that page depends entirely on the kernel, and not the version of the distribution itself. You can still install the 5.7 kernel we provide on Ubuntu 18.04, even if that distribution doesn't provide a 5.7 kernel itself.

**Comment by fkromer** [comment]
@qzed 

> This represents the state of the current kernels, both 5.7/latest and 4.19/LTS.

Alright I was missing the info about to what kernel versions the matrix applies to. In this case I'm more than happy with what's already in the wiki :slightly_smiling_face:

> Having those features split out by Ubuntu version does not make much sense to me

You are right. The use case that someone does not want to use a far newer kernel version than officially provided by the distro should be really quite uncommon.

The open, device specific issues should all be OS related misconfigurations then, right?

**Comment by qzed** [comment]
> Alright I was missing the info about to what kernel versions the matrix applies to. In this case I'm more than happy with what's already in the wiki slightly_smiling_face

We try to keep all kernel versions on the same support level. There are notable differences though, specifically in touch support, due to some upstream changes that we can't easily work around. Apart from touch though (which I believe is highlighted in multiple sections on the wiki) and newer devices (IIRC SP7, SL3, SB3, etc.) requiring newer kernels due to upstream support  (which is pretty much out of our hands) there should not be any feature difference between the kernels.

> The open, device specific issues should all be OS related misconfigurations then, right?

As far as I can tell, (mostly) yes. Although there may of course still be bugs and regressions in the drivers, but in general stuff like battery status etc. should work if it's indicated in the matrix.
