### ISSUE TITLE
Booting from usb problem

### ISSUE THREAD

**Issue by introlinux** [linux-surface/linux-surface#243]
Hi, I'm trying to boot from a usb with my personalized debian system. I installed the linux-surface-kernel but I don't know why it doesn't boot. If I plug the pendrive in other laptops, it boots without problems and detects all hardware perfectly with this kernel, but in Surface Book 3 I don't know what could be the problem. 
I have all firmwares updated.
I made a video so you could see what I comment:
[https://youtu.be/5PePYEzv2-g](https://youtu.be/5PePYEzv2-g)
Any clue how to fix it?
Thanks in advance.

**Comment by archseer** [comment]
4.19 is too old for Surface Book 3/Surface Laptop 3/SP7. I think the Ice Lake support might be missing back then but there was also an issue pre-5.4 that made it unbootable. [We carried a patch for it and it shipped upstream a while ago](https://github.com/linux-surface/linux-surface/blob/master/patches/5.3/0009-ioremap_uc.patch).

There was a quick workaround during the install process: https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#installation

> gen7: If you are having issues with the boot process hanging (and your linux is older than 5.5), temporarily add modprobe.blacklist=intel_lpss_pci to the boot params (Press e on the bootloader screen) for the duration of the install. The custom kernel includes a patch for this issue, and forgetting to remove the parameter afterwards will break things.

I recommend you use the latest kernel (5.8 is about to be published with some major changes, iptsd). 4.19 makes sense on some older devices where the multitouch driver still worked, but that driver won't work with any of the new lineup because of the hardware/firmware changes anyway.

**Comment by introlinux** [comment]
Ok, thanks.
Then, touchscreen doesn't work with 5.8? Or only multitouch functionality?

**Comment by introlinux** [comment]
I have more datas and they are strange, because I tryed the original kernel of my distribution (an older 4.6) and it booted SB3 (but obviously without keyboard or touchpad).

**Comment by qzed** [comment]
You won't get touch support for SB3 (and SL3/SP7) on v4.19 anyways. At the moment, 5.7 (and if it's out 5.8) is probably your best bet, but touchscreen support isn't really there yet for those devices (not sure what the exact status is right now, @StollD should have more info on that).

**Comment by archseer** [comment]
Tracking issue for gen7: https://github.com/linux-surface/intel-precise-touch/issues/4
