### ISSUE TITLE
Consider signing up for Github sponsors

### ISSUE THREAD

**Issue by danielzfranklin** [linux-surface/linux-surface#26]
I don't know if it's worth your time, but if it was available I'd donate $50. If you sign up by Jan 1 GitHub will match it.

https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors

**Comment by meck93** [comment]
Yes, I agree. You guys are doing awesome work and should really consider signing up.

**Comment by espectalll** [comment]
Either that or some alternative like LiberaPay, OpenCollectives or Patreon would be neat

**Comment by qzed** [comment]
As this came up again in #241: I'd be open for something like Github Sponsors (as long as I'm not the only one here...), but I think there needs to go some thought into this (and I have pretty much no experience wrt. to this, so input is welcome). My two main concerns are a) fair distribution of the money (we're a team after all) and 2) taxation procedure.

The latter is fairly straightforward if it's just a single person (at least in Germany this basically counts as salary from independent work), but AFAIK it gets a bit more complicated as soon as you're a group/organization (especially if it's one recognized under the law).

If I've seen that correctly, Github Sponsors (on its own) lets you only sponsor individual (sponsor-enabled) developers. Setting that up would probably be easiest (basically everyone of us has to set up Github Sponsors for himself) and distribution of the money would go to the sponsors, meaning you as sponsor decide how many each dev gets individually. Also that seems to work only up to a maximum of 4 developers. Taxation would have to be handled by the receiver, individually (AFAIK there isn't any legal "organization", as donations go directly to the devs). I also couldn't figure out if there are one-time payments possible (would be a bit of a bummer if not).

LiberaPay seems to be pretty similar, except that distribution ratio is set by developers, which could benefit "smaller"/more hidden developers if we ever have more people on the core team. Sponsorships are AFAIK directly forwarded, which pretty much means that there is no legal "organization" between (which AFAIK makes things easier for taxation).

OpenCollective seems to represent a (more or less) full organization, and also seems to take care of (some of?) the taxation (AFAIK it handles taxation for the org in-between, so each dev is still responsible for his/her income tax, but the in-between stuff would be gone/simplified). Would probably be more scalable in the long term, but IMHO we can always set that up later. On the other hand, OpenCollective has transaction fees. Could also be a bit too much management overhead for us right now (as it seems to be targeted at larger groups).

@StollD any opinions on this?

**Comment by StollD** [comment]
To me, LiberaPay looks like the simpler option, just make an account, connect your PayPal and go. The downside of LiberaPay is that they intentionally don't support one-time donations. 

The documentation for GitHub sponsors kinda sucks to be honest, and it seems like you need to fill out a bunch of tax forms and send them to GitHub for approval?

OpenCollective seems more like a platform for groups who want to strictly reuse all donations for the project itself, with having to declare and approve expenses etc. Since we don't really have expenses for the project, that seems a bit unnecessary. 

All this is from a 5 minute look at the respective homepages and / or setup guides, so maybe I'm totally wrong. But I'd go with the simplest option (for both, us and the user who wants to donate), which seems to be LiberaPay.

**Comment by qzed** [comment]
> The documentation for GitHub sponsors kinda sucks to be honest

Yeah, a bit.

> it seems like you need to fill out a bunch of tax forms and send them to GitHub for approval?

Hmm yeah, haven't noticed that before, but [looks like it](https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/tax-information-for-github-sponsors). Doesn't look like it's overly complicated though. If I understand that correctly, it's so that Github doesn't have to pay taxes for payment transfers where the income receiver is in another country. I'll probably try and set up my account for Github Sponsors. If that works out well, I think you should consider that too (this doesn't have to be linux-surface project related).

I also just realized that you can set up a whole organization for sponsorship (e.g. https://github.com/sponsors/elementary, so we could theoretically set up the linux-surface org for that). For that, we'd have to set up a bank account though (see [doc.](https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-organization#submitting-your-bank-information)), and with that we'd have to handle taxes for that and deal with payouts ourselves, and since that's basically an organization then we'd probably have to register that too. In short: Stuff I'd rather not like to deal with. I don't think that makes much sense for our small group.

> OpenCollective seems more like a platform for groups who want to strictly reuse all donations for the project itself, with having to declare and approve expenses etc. Since we don't really have expenses for the project, that seems a bit unnecessary.

I mean we could write up some sort of pay-out for work as expense (I believe that's how other orgs do that), but that's kind of what I meant with management overhead. I agree with you there, I don't really see the need or benefit for us right now. Could be a bit more transparent if we'd want to lets say fundraise for a Surface Pro X if someone of us had the time to look at implementing support for that, but quite honestly, I don't think we're on that level right now.

Also I don't really want to see the donations as "pay for work", rather as (motivational) support if you think this is a good project. I don't want to set any expectations that if you donate I'll spend more time on this project/if you don't donate I won't work on this any more. This will always be a side project for me and I'll continue working with or without donations on this on my free time (which comes second to university right now). OpenCollective (and resulting payout transactions) could, I think, set up an image like that.

> All this is from a 5 minute look at the respective homepages and / or setup guides, so maybe I'm totally wrong. But I'd go with the simplest option (for both, us and the user who wants to donate), which seems to be LiberaPay.

I tend to agree on that. Also, this doesn't have to be exclusive: We can set up LiberaPay and still (maybe later) add our individual Github Sponsor profiles/links, once all of you set those up (seems like you can add up to 4 of those, which would still work for us).

**Comment by qzed** [comment]
We've decided to set up a [liberapay team](https://liberapay.com/linux-surface/) as that seems to be the easiest solution for us at the moment.
