### ISSUE TITLE
Secure boot on surface book 2

### ISSUE THREAD

**Issue by deb75** [linux-surface/linux-surface#29]
Hello,

I currently run debian/buster on a surface book 2 from latest jakeday's kernel. To do so, I disabled secure boot.

I would like to enable again secure boot, however I am totally new with secure boot and signing kernels and I am really afraid on bricking or messiing something. Furthermore, my boot loaded is`refind`.

I cannot figure out clearly the steps for this boot loader. For what I understand, I first need to sign the `refind` boot loader with microsoft keys, then the linux kernel. Could someone explain me how to proceed ?

Regards

**Comment by qzed** [comment]
To set up secure-boot you actually have two options on Linux at the moment: `PreLoader` or `shim`. I'd recommend `shim` for this kernel, as we provide pre-signed images for that. The overall idea with shim and refind (or any other bootloader for that matter) is: UEFI loads shim (which is signed and trusted by Microsoft) and shim in turn loads refind, which then loads the kernel.

You need to tell shim however that refind is a trusted application, which you can again do in two different ways: Using hashes or using a Machine Owner Key. Luckily, refind provides a `refind-install` tool that does all this for you, see e.g. https://wiki.archlinux.org/index.php/REFInd#Using_shim (while this is for Arch Linux, it should be similar on Debian).

If you've set that up, you can then use refind to load your kernel. However, you again need to tell the system that the kernel is trusted, which is why you either need to enroll the hash or sign it. The kernels provided here are already signed, so you only need to enroll the key as described in the [wiki](https://github.com/linux-surface/linux-surface/wiki/Secure-Boot#using-the-provided-secure-boot-certificate). Basically via `mokutil` that boils down to `sudo mokutil --import MOK.cer` with the key provided in this repo.

**Comment by qzed** [comment]
Also you can't brick anything, as you can just disable secure-boot again if something failed.

**Comment by qzed** [comment]
I assume this has been resolved. Feel free to re-open if I'm mistaken.

**Comment by deb75** [comment]
As far as I understand, i need : 
1. create a MOK key
```
openssl req -newkey rsa:4096 -nodes -keyout MOK.key -new -x509 -sha256 -days 3650 -subj "/CN=my Machine Owner Key/" -out MOK.crt
openssl x509 -outform DER -in MOK.crt -out MOK.cer
```

2. Install Refind with shim and local keys
```
refind-install --shim /usr/share/shim-signed/shimx64.efi --localkeys
```
3. SIgn my kernel with the same key
```
sbsign --key /etc/refind.d/keys/refind_local.key --cert /etc/refind.d/keys/refind_local.crt --output /boot/vmlinuz-linux /boot/vmlinuz-linux
```

Is it enough ? I still do not understand what enroll a key means.

**Comment by qzed** [comment]
You only need to sign the kernel if you want to use your own certificate or you compile it on your own. Otherwise you can skip the steps you've posted.

Enrolling the key means telling shim that it's a trusted key. You can do that via `mokutil --import MOK.cer` (followed by a re-boot after which you have to follow the instructions on screen) as described on the wiki (or if you want to use one of the releases here, installing the `linux-surface-secureboot-mok` package will do that for you automatically).

**Comment by deb75** [comment]
Yes, I compile my own kernel.

If I understand well, after having created my own key, I install `refind` with `shim` : 
```
refind-install --shim /usr/share/shim-signed/shimx64.efi --localkeys
```
so that `refind` will sign itself with my key, but then I need to tell `shim`, as you say,
it is a trusted key : 
```
mokutil --import /path/to/my/mok.cer
``` 
I also have to dign my own kernel with the private part of the key and then I reboot.

During the boot, I will be asked bu MokManager to enroll the key with the password I
used for `mokutil`.

**Comment by qzed** [comment]
That is correct.

**Comment by deb75** [comment]
When I choose grub from the refind menu, it is rejected, should i sign the grub loader `grubx64.efi` like I signed the linux kernel ? Also, there are two files : `/boot/efi/EFI/debian/grub64.efi` and `/boot/efi/EFI/refind/grub64.efi`, which one is used ?

**Comment by qzed** [comment]
`refind/grubx64.efi` is the refind bootloader, as far as I remember. Shim always expects a `grubx64.efi` thus it's not named `refind.efi`. Basically the chain is: `shim.efi` -> `grubx64.efi` (in the same directory as `shim.efi` -> whatever you select in refind. So to make shim work with refind, refind has to be named `grubx64.efi`  (see also https://wiki.archlinux.org/index.php/Secure_Boot#Set_up_shim). I think `debian/grubx64.efi` is the actual grub bootloader. If that's unsigned you'll have to sign it (or alternatively enroll its hash via MokManager, that should also work; You can do that directly from the refind screen).

**Comment by deb75** [comment]
Thanks for your answeer.

I did sign the `debian/grubx64.efi` and refind agrees to launch grub, but it stops with the error 
```
error: Secure Boot forbids loading module from (hd0,gpt2)/boot/grub/x86_64-efi/normal.mod.
```
I think it is because grub executes some modules which are not signed. So I replaced `debian/grubx64.efi`  by another generated with  `grub-mkstandalone` which includes all modules by default. However, I still get the same error.

**Comment by qzed** [comment]
Hmm, I can't help you with that. By the way, is there any reason why you want to load grub via refind and not use refind itself instead?

**Comment by deb75** [comment]
You are right. I could get rid of grub, I just wanted to understand why it was not working.

**Comment by gegnew** [comment]
> To set up secure-boot you actually have two options on Linux at the moment: `PreLoader` or `shim`. I'd recommend `shim` for this kernel, as we provide pre-signed images for that. The overall idea with shim and refind (or any other bootloader for that matter) is: UEFI loads shim (which is signed and trusted by Microsoft) and shim in turn loads refind, which then loads the kernel.
> 
> You need to tell shim however that refind is a trusted application, which you can again do in two different ways: Using hashes or using a Machine Owner Key. Luckily, refind provides a `refind-install` tool that does all this for you, see e.g. https://wiki.archlinux.org/index.php/REFInd#Using_shim (while this is for Arch Linux, it should be similar on Debian).
> 
> If you've set that up, you can then use refind to load your kernel. However, you again need to tell the system that the kernel is trusted, which is why you either need to enroll the hash or sign it. The kernels provided here are already signed, so you only need to enroll the key as described in the [wiki](https://github.com/linux-surface/linux-surface/wiki/Secure-Boot#using-the-provided-secure-boot-certificate). Basically via `mokutil` that boils down to `sudo mokutil --import MOK.cer` with the key provided in this repo.

I'm not sure what I'm doing wrong here, but running refind-install per the link you've provided results in an emergency shell on reboot. Can you be a little more explicit about the steps to set up refind/shim?

**Comment by qzed** [comment]
Are there any indications why you're getting dropped into an emergency shell? If the emergency shell is provided by a kernel, have you tried booting into a different kernel? Or is this some EFI, refind, or grub shell? Do you have secureboot turned off/does it work with secureboot turned off? Any errors while running `refind-install`? What distro are you on?

On some distributions (Ubuntu, Fedora, not sure about Debian) secureboot and a bootloader supporting it are already set up, so doing that manually is not necessary. The general assumption of our guide (and my recommendation) is: Have secureboot set up before installing our kernel, or if you already have it installed, set it up for the official distribution kernel first. Then via secureboot boot into the official distribution kernel and set up secureboot for the linux-surface kernel from there.

If you're on Arch, the way to set up refind for secureboot with shim and MOKs (that's just what we recommend, of course you can also set it up with hashes, or with a patched grub if you don't like refind, ...) is pretty much:
1. Install the `shim-signed`, `sbsigntools`, and `refind` packages.
2. Run `refind-install --shim /usr/share/shim-signed/shimx64.efi --localkeys`. This will a) install refind, b) generate a local MOK for you to sign stuff with, c) automatically sign refind itself with the generated keys, and d) copy the public key for you to the EFI partition, where you'll need to retreive it later (step 5).
3. Sign the kernel: Run `sbsign --key /etc/refind.d/keys/refind_local.key --cert /etc/refind.d/keys/refind_local.crt --output /boot/vmlinuz-linux /boot/vmlinuz-linux`, replacing `vmlinuz-linux` with the kernel you want signed. Repeat this for every kernel you want signed.
4. Reboot to UEFI, enable secure-boot. If you've been using grub before, switch to the refind entry.
5. Reboot normally. You should now see refind. In there, select the MokManager tool, where you should find an option add or enroll key (or something similar). Select that, then select the publik key generated by refind and confirm. This should be `esp/EFI/refind/keys/refind_local.cer`, where `esp` is your EFI system partition.
6. Boot into the signed kernel via refind.

That's pretty much all on the Arch wiki (with maybe a bit more detail), which also provides some more hints on how to set up automated kernel signing for the non-signed distribution kernels via pacman hooks. Those steps should also work on other distributions, but the paths might differ. Note that this is only the generic setup, which should work for any kernel, but as I'll discuss below, you should set this up first for a non-signed/official distribution kernel due to some issues you might encounter.

There is a bit of a problem though that you might run into when doing this manual setup: When a kernel has been signed with multiple keys, both keys must be known to shim. That means that either you can't boot the linux-surface kernel on your first boot, or you'll need to manually add the key by copying the public key (`/usr/share/linux-surface-secureboot/surface.cer` on Arch) to the EFI partition and adding it via the MokManager, similar to adding the key created by refind. Also the `mokutil` tool doesn't work with secureboot disabled, so installing the `linux-surface-secureboot-mok` package doesn't automatically add the key if secureboot is disabled.

Once you have secureboot set up for the default kernel of your distribution and have booted into it with it enabled, install the `linux-surface-secureboot-mok` package. If you have installed that previously while secureboot was turned off, uninstall it and then install it again (simple re-installation won't work). This will trigger the script automatically adding the key via mokutil. Then reboot, and if MokManager does not open automatically, boot into it and confirm the addition of the key (i.e. follow the steps printed when installing the package).
