### ISSUE TITLE
Shutdown not working

### ISSUE THREAD

**Issue by raspbeguy** [linux-surface/linux-surface#337]
When powering off my SP4, for instance with GNOME menu, screen goes black with a blinking cursor but the machine doesn't shut down (same for reboot). I have to force it by long pressing the power button.

However powering off works out of the box with main archlinux kernel.

### Environment

- Hardware model: Surface Pro 4
- Kernel version: 5.9.8-arch1-1-surface
- Distribution: Arch Linux

**Comment by Tim024** [comment]
I have the same problem with my Surface Laptop 3, on Ubuntu 20.04.1 and kernel 5.9.1-surface.

**Comment by provegard** [comment]
Same here. I first associated it with the 5.9.8 kernel, but it's the same problem if I boot with 5.9.6. After waiting a while I get this:

![shutdown](https://user-images.githubusercontent.com/795010/99979850-de761100-2da7-11eb-8d42-a37da74b9f18.jpg)

This is on a Surface Book 2.

**Comment by provegard** [comment]
I just did a complete reinstall and shutdown/restart works now, with kernel `5.9.8-surface`. Before the problem started last time, I installed `tlp` - which I haven't done yet after the reinstall. Could `tlp` result in something like the above?

**Comment by qzed** [comment]
I guess tlp could cause this, in fact pretty much any task doing an IOCTL or otherwise communicating with the kernel can cause something like that. Based on the messages all we can say for certain is that some process is blocking inside the kernel (e.g. deadlock or something). Based on the systemd output I'd guess it's `wpa_supplicant` as it indicates it's waiting for that to shut down.

I think there should be some way to get a stack-trace from that task (which would help us track down what's causing this), at least that seems to be the default behavior on my Arch install. I have no clue how to enable that though. I guess you could try if stopping the `NetworkManager`/ the `wpa_supplicant` services manually will hang too.

**Comment by raspbeguy** [comment]
`tlp` is not installed here.

After enabling `debug` kernel option, here is my screen at shutdown:

![IMG_20201124_180547](https://user-images.githubusercontent.com/1781287/100130479-09816300-2e83-11eb-9264-1694c002bdc3.jpg)

**Comment by qzed** [comment]
@raspbeguy I can't see anything out of the ordinary in your screenshot. The IPTS stop message maybe comes a bit late, so you could try to unload the `ipts` module before shutting down. Apart from that, you could try experimenting with unloading other modules or shutting down services.

**Comment by raspbeguy** [comment]
I disabled IOMMU and now it works.

**Comment by qzed** [comment]
Interesting. @StollD IIRC there were issues with IOMMU in the past?
