### ISSUE TITLE
License of this repository

### ISSUE THREAD

**Issue by SamLukeYes** [linux-surface/linux-surface#356]
I don't see any license file in this repo. Would you please add one?

**Comment by qzed** [comment]
I'm not entirely sure how licensing works in a repo like this. Generally, the patches are licensed under the license of either the code that they provide or the code that they modify, so generally something like GPLv2 since it's kernel stuff. Other parts of the repo (specifically the configs) may not be licensable at all (or rather any license on those cannot be enforced) as they don't really provide anything of substance.

I guess we could add a GPLv2 license file. @StollD, @archseer any ideas/comments on this?

**Comment by archseer** [comment]
Patches are licensed based on the original source, since they're a derivative work (otherwise you could bypass GPL by simply using patches on top of a source). Modules we built ourselves have [licensing information](https://github.com/linux-surface/surface-aggregator-module/blob/aaad476104318d5050b9981f1bd4f5988b3d938d/module/src/clients/surface_hid.c#L924) included.

If we drop in a license we'd probably need to denote these exceptions along with it.

**Comment by archseer** [comment]
So the only thing not having a clear license is the packaging. I'm not sure if licensing the package definitions is really a thing, I can't find any license on the arch linux kernel package for example: https://github.com/archlinux/svntogit-packages/tree/packages/linux/trunk

**Comment by qzed** [comment]
> If we drop in a license we'd probably need to denote these exceptions along with it.

Right, I thought as much.

> So the only thing not having a clear license is the packaging. I'm not sure if licensing the package definitions is really a thing, I can't find any license on the arch linux kernel package for example: https://github.com/archlinux/svntogit-packages/tree/packages/linux/trunk

And maybe the wiki, if you consider that part of the repo.

I think packaging files may not strictly be licensable as they don't really provide anything of significance on their own, they're always bound to a project. I.e. unless you're doing something completely new and crazy, a packaging script will always roughly look the same for the platform/format you're targeting. I think copyright only applies to what's called "expressive" work, and I think configs and packaging scripts are not really that. (Also I think the Arch PKGBUILD we use is based on the official Arch PKGBUILD and I'm not comfortable putting a license on that if the original one doesn't have one).

Also note that adding a license file does not equal licensing content under that license (since we're re-distributing GPL code, we might even have to add or link to one, actually). Strictly speaking I believe we'd have to mark all files under that license with a license header. We should still write that (and exceptions, which is pretty much the whole repo) down though as in practice those license headers are not always used here on GitHub. Not sure how you would write something like this down in legalese though.

Maybe a license section in the readme? E.g.:

> ## License
> This repository contains patches, which are either derivative work targeting a specific already licensed source, i.e. parts of the Linux kernel, or introduce new parts to the Linux kernel. These patches fall thus, if not explicitly stated otherwise, under the license of the source they are targeting, or if they introduce new code, the license they explicitly specify inside of the patch. Please refer to the specific patch and source in question for further information. License texts can be obtained at https://github.com/torvalds/linux/tree/master/LICENSES.

**Comment by archseer** [comment]
I think I'm okay with that declaration in the README. 👍🏻

**Comment by StollD** [comment]
Looks good to me too.

**Comment by qzed** [comment]
Perfect, I'll add that then.
