### ISSUE TITLE
Surface Book 2 Freeze on Detatch

### ISSUE THREAD

**Issue by jonkatz6** [linux-surface/linux-surface#358]
Everything seems to be running fine besides the detach feature. 
when the keyboard is detached from the tablet, the tablet immediately freezes. No input is taken, screen is frozen, no rotation, but it will continue to play the audio of whatever was playing. The only way out seems to be a forced shutdown, reattaching does not solve the issue.
Please advise.

### Environment
- Hardware model: <Surface Book 2 13 inch Nvidia 1050>
- Kernel version: <Linux JKSB 5.9.13-surface>
- Distribution: <debian ubuntu with gnome>

**Comment by qzed** [comment]
I suspect you have the nvidia (or nouveau) driver loaded and running, in which case that behavior is to be expected. Make sure to either blacklisted it or remove it manually before you detach the top. Note that some things (like the X-server/Gnome) can prevent you from being able to unload the driver, so your best option if you want to be able to detach the top is to blacklist it. If you need the dGPU and you want to be able do detach, you'll have to manually un-blacklist it after Gnome/the X-server has loaded and use something like optirun/primusrun/...

**Comment by PiecePaperCode** [comment]
If you use the nvidia driver.
There you can select the intel **(Power Saving Mode)**.
![image](https://user-images.githubusercontent.com/40020346/104590859-358fb800-566c-11eb-8b45-72e7946539b0.png)
Detaching will not crash your system.
Another Method if you want to use nvidia is to set it to **(NVIDIA On-Demand)**
All Applications will still start with Intel except if you start apps with the nvidia. in Ubuntu its called use **(descrede graphics)** on right click. Detaching will not crash your system only if you are having an app using it. If you are not doing lots of work leaving it disabled is the state to be desired, because it will drain your battery real fast and nvidia will clock down heavily if on battery making it unusable when not plugged in.

Dont use **(NVIDIA Performance Mode)** it will clock down when on battery making your System unusuable.
This is an issue that can be addressed on another fix but your question is answered and can be @jonkatz6 closed.

**Comment by qzed** [comment]
@PiecePaperCode Thanks for that info, I've linked to your comment in the [Surface Hotplug Wiki](https://github.com/linux-surface/surface-hotplug/wiki/Runtime-Power-Management), feel free to edit that.

Closing as this should be resolved.
