### ISSUE TITLE
Re-add Surface 3 SPI DMA patch

### ISSUE THREAD

**Issue by hadess** [linux-surface/linux-surface#368]
This patch seems to have been dropped at some point:
https://github.com/linux-surface/kernel/pull/24

Was it obsoleted and I missed it? I guess the Surface 3 users are pretty few and far between.

**Comment by qzed** [comment]
This patch was a workaround and has been dropped (see https://github.com/linux-surface/kernel/commit/df179b9daad35284434bff9cb2612866ec03e1f5) as the underlying issue should have be fixed with https://github.com/torvalds/linux/commit/99ba8b9b0d9780e9937eb1d488d120e9e5c2533d. I believe that commit has also been backported to the relevant LTS kernels.

**Comment by hadess** [comment]
I was hunting a hang on my system after a couple of minutes of light usage and was wondering why this patch disappeared. I guess it's probably something else. Thanks for references!
