### ISSUE TITLE
Getting to work Surface-LTS on Ubuntu 20.04

### ISSUE THREAD

**Issue by lx07** [linux-surface/linux-surface#384]
Could you add the installation configuration for getting to run an LTS Kernel on Ubuntu 20.04?

`sudo apt install linux-image-surface-lts linux-headers-surface-lts iptsd libwacom-surface`

Is it that?
Does iptsd have to be disabled for the LTS-Kernel? 
Currently I am not able to get Touch on the LTS, wheras it was working some months ago.

I want to experiment with the LTS-Kernel because I believe it is the solution to #319 

**Solved**: I was missing the **surface-ipts-firmware** so the correct installation for the LTS-Kernel would be
`sudo apt install linux-image-surface-lts linux-headers-surface-lts surface-ipts-firmware libwacom-surface`

**Comment by lx07** [comment]
Sorry, one more question @qzed , do you also provide surface-lts kernels for the Fedora project?

**Comment by qzed** [comment]
Not at the moment. You'd have to convince @StollD for that, he manages the Fedora builds.

**Comment by StollD** [comment]
I don't plan to package the 4.19 lts for fedora at the moment, sorry. Mainly because I wouldn't use it and don't really have the time for it, but also because I think it doesn't fit the fedora philosophy. They move fast and use new features when they are available. And I feel like using a two year old kernel *will* cause issues there. Take for example btrfs: If you do a fresh install of Fedora 33 your default file system will be btrfs. If you now switch to the 4.19 LTS kernel you will miss two years of fixes and performance improvements.

However, if anyone wants to package 4.19 for Fedora I'm happy to help if it's needed, either on GitHub or IRC / Matrix.
