### ISSUE TITLE
Refind misconfiguration prevent from booting the newly updated kernel?

### ISSUE THREAD

**Issue by alexanderi96** [linux-surface/linux-surface#391]
Hi there! I've searched if someone experienced a problem like mine, but i was not able to find anything useful.

Let's go straight to the problem.
I used to have Pop OS on my surface pro 2017, coupled with the Refind bootloader in order to have a more pleasent and touch friendly boot menu.
Till I stuck with this configuration everything was going ok, and every since I updated the kernel Refind took the new one without any problem.
Last week I decided to go back to Arch in order to see if the wifi performance was going to be better and more stable compared to Pop OS (turned out that yes, the speed i significantly better and more stable, don't ask me why lol).
Refind was working fine and it was able to see my arch boot entry without any additional configuration, but as soon as I installed the surface kernel I had no chance to boot from it because it keept me saying 

```  
:: mounting '/dev/nvme0n1p5' on real root
mount: /new_root: unknown filesystem type 'ext4'. You are now being dropped into an emergency shell.
sh: can't access tty: Job control turned off
```
And the only option that I had was booting with the generic kernel, till I found an issue here on Github (maybe in the Refind issues, I don't remember) where someone suggested to add a row in the ```/boot/refind_linux.conf``` file.
I edited it in order to make it compliant to my needs and this is the result.
```
"Boot Surface kernel" "root=UUID=partition-uuid add_efi_memmap rootfstype=ext4 initrd=/boot/intel-ucode.img initrd=/boot/initramfs-linux-surface.img loglevel=3 vga=current"
```
Being able to boot my surface kernel.

But now, after updating to the 5.10.10 it is doing the same thing and I must manually select the correct option before booting into Arch in order to boot the newly installed kernel.

Maybe I'm missing something or misconfigured something, hope that someone can clearify what I'm doing wrong :)
Thanks! 

### Environment

- Hardware model: Surface Pro 5 (2017)
- Kernel version: Linux sasfifsos 5.10.10-arch1-1-surface #1 SMP PREEMPT Sun, 24 Jan 2021 23:49:58 +0000 x86_64 GNU/Linux
- Distribution: Arch Linux

**Comment by qzed** [comment]
I think the `unknown filesystem type 'ext4'` could indicate that the module for ext4 is missing from the initram. No clue why it would complain about that otherwise. Also no clue why it would be missing in the first place though...

Regarding missing kernel options, they're a) hidden away and you'll have to use F2 to display them and b) you'll have to add `linux-surface` (and if you're using LTS `linux-surface-lts`) to refind.conf for refind's auto-detection to to work (search for `extra_kernel_version_strings` or consult the [Arch wiki](https://wiki.archlinux.org/index.php/REFInd#For_kernels_automatically_detected_by_rEFInd)).

Regarding your `/boot/refind_linux.conf` file, I assume you've replaced `partition-uuid` with the actual partition UUID of the root partition?

I've personally set up refind via manual boot entries to make sure that I'm always booting into the Surface kernel, so that's a thing that you might want to look into.

**Comment by alexanderi96** [comment]
Thank you for your answer!
After a couple of try I managed to set it up properly (I just hope that the next update dont't mess it up lol).
First of all I tried to define the ```linux-surface``` kernel in the ```extra_kernel_version_settings``` parameter in the ```refind.conf``` without any luck.
Then I tried to uncomment the ```default_selection``` parameter, specifying the ```vmlinuz-linux-surface``` still without any luck.
My last attempt (and the good one) was modifying directly the Arch Linux menuentry, specitying there the correct loader, initrd and fallback!

Regarding the ```/boot/refind_linux.conf``` file, yes, I did't included the actual partition UUID in the previous comment, I don't know why, but it's ok, because I decided to get rid of that config file, because now it's working properly even without it.
