### ISSUE TITLE
Errors installing latest kernel

### ISSUE THREAD

**Issue by afalout** [linux-surface/linux-surface#413]
Dear devs,

I see 2 errors when installing latest surface kernel:
   1) VirtualBox kernel module fails to compile against new kernel (it worked fine so far)
   2) Number of warnings about "Possible missing firmware ... for module i915" (messages did not appear before)

SP4, 5.11.5-surface-1, Kubuntu 20.10

Details:

...
Setting up linux-image-5.11.5-surface (5.11.5-surface-1) ...
 * dkms: running auto installation service for kernel 5.11.5-surface                                                
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.11.5-surface -C /lib/modules/5.11.5-surface/build M=/var/lib/dkms/virtualbox/6.1.16/build..........(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-5.11.5-surface is not supported
Error! Bad return status for module build on kernel: 5.11.5-surface (x86_64)
Consult /var/lib/dkms/virtualbox/6.1.16/build/make.log for more information.
                                                                                                             [ OK ]
update-initramfs: Generating /boot/initrd.img-5.11.5-surface
W: Possible missing firmware /lib/firmware/i915/skl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/glk_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/cml_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/icl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/ehl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/tgl_guc_49.0.1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/dg1_dmc_ver2_02.bin for module i915
I: The initramfs will attempt to resume from /dev/dm-2
...

/var/lib/dkms/virtualbox/6.1.16/build/make.log:
...
  CC [M]  /var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/SUPR0IdcClient-linux.o
/var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.c: In function ‘vboxNetFltNeedsLinkState’:
/var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.c:1761:47: error: invalid use of undefined type ‘const struct ethtool_ops’
 1761 |     if (pDev->ethtool_ops && pDev->ethtool_ops->get_drvinfo)
      |                                               ^~
/var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.c:1763:32: error: storage size of ‘Info’ isn’t known
 1763 |         struct ethtool_drvinfo Info;
      |                                ^~~~
/var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.c:1766:20: error: ‘ETHTOOL_GDRVINFO’ undeclared (first use in this function)
 1766 |         Info.cmd = ETHTOOL_GDRVINFO;
      |                    ^~~~~~~~~~~~~~~~
/var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.c:1766:20: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.c:1767:26: error: invalid use of undefined type ‘const struct ethtool_ops’
 1767 |         pDev->ethtool_ops->get_drvinfo(pDev, &Info);
      |                          ^~
/var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.c:1763:32: warning: unused variable ‘Info’ [-Wunused-variable]
 1763 |         struct ethtool_drvinfo Info;
      |                                ^~~~
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt/linux/VBoxNetFlt-linux.o] Error 1
make[1]: *** [scripts/Makefile.build:496: /var/lib/dkms/virtualbox/6.1.16/build/vboxnetflt] Error 2
make: *** [Makefile:1806: /var/lib/dkms/virtualbox/6.1.16/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.11.5-surface'

Thanks for any advice.
Andrej

**Comment by qzed** [comment]
1. Seems like VirtualBox (or at least the version you have) doesn't support v5.11 kernels yet.
2. Those are firmware files that likely have been added with the v5.11 kernel. You might want to check if there's an updated firmware package available for your distribution.

**Comment by marciof** [comment]
1. I also have a v5.11 kernel (v5.11.13), and installing a [VirtualBox test build](https://www.virtualbox.org/wiki/Testbuilds) ([6.1.x revision 143767](https://www.virtualbox.org/download/testcase/VirtualBox-6.1.19-143767-Linux_amd64.run)) seems to work for me.

**Comment by qzed** [comment]
@marciof Thanks for the feedback! Closing this issue based on that.

Some words on those kinds of issues (i.e. incompatibility of external/out-of-tree and possibly out-of-date modules with some specific kernel version), in general:
- Unless this is specifically a "this does not work with the Surface kernels"-problem as opposed to a "this does not work with all version X.Y kernels"-problem, the external/out-of-tree module should be updated and (if necessary) you should file a bug with the provider of that module. Most likely you will find that your distribution, e.g. Ubuntu, just doesn't provide the latest version of that module yet (because that distro is centered around some older kernel), so you should either try to update your distribution version or get that module from somewhere else, e.g. backports or a PPA from the provider of the module.
- Instead of updating the module, you can also always switch to our `-lts` variants and check if the module works there. Since those are currently v4.19 (so pretty old), the probability of that working is pretty high.

Unfortunately (mostly since distributions like Debian or Ubuntu are focused on a very specific kernel version that is quite often _not_ the latest version, i.e. not the version on which we base our packages on), this is an issue that's going to come up over and over again. The one thing that we could do is provide kernels for all major version in use (e.g. v5.10, v5.4, ...) but I don't particularly fancy maintaining yet more versions.

**Comment by marciof** [comment]
@qzed oh, I didn't realize that there are "-lts" versions of the Surface kernel available. Good to know, thanks. By the way, is it risky to switch now from my current v5.11.13 to an LTS one?

**Comment by qzed** [comment]
It should never be risky, as the kernel will be installed in parallel to any other kernels you've got installed, so you can always switch back by just re-booting into a different one (as long as you don't uninstall those, which I don't recommend). You might have to check that you're actually booting into the right kernel and/or change the boot order of the kernels depending on what you want to boot into by default (e.g. so that you don't have to go into the grub extended menu for booting every time).

If the LTS kernels will actually work well is another question. I think for 7th-gen. devices (so SP7, SB3, SL3) it may not since it's just too old for them. I believe there were some fixes and patches regarding those devices that are only available in the newer kernels. With regards to Surface-specific functionality, all kernels should be equal with the exception of touch, which uses the "original" IPTS driver on LTS (that does not work for 7th gen devices, so at least no touch for those there) and the new one for non-LTS.

**Comment by marciof** [comment]
@qzed, I'm getting failures while installing Debian and Windows inside VirtualBox, so maybe I spoke too soon above about it working. Just wanted to report, but I'll investigate some more.
