### ISSUE TITLE
performance settings do not work

### ISSUE THREAD

**Issue by atropos112** [linux-surface/linux-surface#437]
Hi,

I am a surface book 2 user using arch. When I updated to 5.12.2-arch1-1-surface the performance settings stopped working, for example `sudo surface performance get` gives
```
Error: Failed to get current performance mode

Caused by:
    0: Could not access device "/sys/bus/surface_aggregator/devices/01:03:01:00:01/perf_mode"
    1: No such file or directory (os error 2)
```
in fact the directory `/sys/bus/surface_aggregator/devices/01:03:01:00:01/` only has the following 
```
driver  modalias  power  software_node  subsystem  uevent
```

I have recently updated to 5.12.2-arch1-3-surface but the problem persists.  

On a side note, as I was looking to see if there are similar problems i saw someone mention similar issue with profile (which is now resolved). What is the difference between profile and performance ???

**Comment by qzed** [comment]
Two things:
- The performance mode interface has been replaced with the platform profile interface (thus `surface performance` has been replaced with `surface profile` on v5.12 kernels). See [this](https://github.com/linux-surface/linux-surface/issues/96#issuecomment-838706300) announcement post for a bit more details. Since you're on Arch, you might also want to consider installing the [`power-profiles-daemon`](https://aur.archlinux.org/packages/power-profiles-daemon/) (at least if you're using Gnome, since that enables the new UI for that, see https://github.com/linux-surface/linux-surface/issues/436 for what I mean).
- Please you update to `5.12.2-3`, `5.12.2-1` didn't have the new interface enabled.

**Comment by atropos112** [comment]
Thank you for your response, forgot to look at announcement sorry. Okay so the profile is like performance but focuses on more system features to provide desired performance/power saving output cool ! Thank you !

**Comment by qzed** [comment]
It's essentially exactly the same thing, just a different interface. The reason for that change was that the kernel now has a standard, vendor-independent interface, so the idea is that you, in the near-distant future (or right now with the Arch package and Gnome), won't need to use some command line tool any more but that it's all integrated in the desktop environment.
