### ISSUE TITLE
Surface Go WiFi Firmware Download Broken

### ISSUE THREAD

**Issue by n8detar** [linux-surface/linux-surface#440]
The download for the WiFi Firmware fix in the wiki no longer works.

### Environment

- Hardware model: Surface Go

**Comment by MostafaMotahari** [comment]
Yes.
I've this problem too.
The board.bin file download link redirect to Intel website recently instead of downloading bin file.

If any one has that file, please upload it and give the download link. I have problem with my wireless.

The broken download link:
http://www.killernetworking.com/support/K1535_Debian/board.bin

**Comment by zoltantamasvajda** [comment]
I ran into the same issue. Thankfully the wayback machine link works:
[https://web.archive.org/web/20201111213909/http://www.killernetworking.com/support/K1535_Debian/board.bin](https://web.archive.org/web/20201111213909/http://www.killernetworking.com/support/K1535_Debian/board.bin)

**Comment by SwordElucidator** [comment]
Anyone has that file download link? Many thanks!!!!!

**Comment by n8detar** [comment]
> I ran into the same issue. Thankfully the wayback machine link works:
> https://web.archive.org/web/20201111213909/http://www.killernetworking.com/support/K1535_Debian/board.bin


This worked for me. Is there somewhere we can store it to make sure it is always available?

**Comment by qzed** [comment]
I've taken this issue as reason to finally package the board-file workaround. A while ago I've added a [patch](https://github.com/linux-surface/kernel/commit/19d746dc9980d9109b93c9424138d3966c8a67cf) that allows you to select different board and board-2 files via module parameters, and with that it should now be possible to just install a package to apply that fix. That should also make system updates easier.

So can anyone of you try reverting the current fix and install the `surface-ath10k-firmware-override` package and confirm if that's working? All that package does is install the board file as `board-override.bin` and then install a modprobe config with the following line
```
options ath10k_core skip_otp=y override_board=board-override.bin override_board2=none
```

This should be equivalent to the workaround on the Surface Go wiki page, i.e. cause `board-override.bin` to be loaded instead of `board.bin` and `board-2.bin` to be ignored/not loaded.

See https://github.com/linux-surface/ath10k-firmware-override for details.

**Comment by n8detar** [comment]
> I've taken this issue as reason to finally package the board-file workaround. A while ago I've added a [patch](https://github.com/linux-surface/kernel/commit/19d746dc9980d9109b93c9424138d3966c8a67cf) that allows you to select different board and board-2 files via module parameters, and with that it should now be possible to just install a package to apply that fix. That should also make system updates easier.
> 
> So can anyone of you try reverting the current fix and install the `surface-ath10k-firmware-override` package and confirm if that's working? All that package does is install the board file as `board-override.bin` and then install a modprobe config with the following line
> 
> ```
> options ath10k_core skip_otp=y override_board=board-override.bin override_board2=none
> ```
> 
> This should be equivalent to the workaround documented on the Surface Go wiki page, i.e. cause `board-override.bin` to be loaded instead of `board.bin` and `board-2.bin` to be ignored/not loaded.
> 
> See https://github.com/linux-surface/ath10k-firmware-override for details.

This may be because I removed `/usr/lib/firmware/ath10k/QCA6174/hw{2.1,3.0}/board-2.bin` before I realized the link was broken, but when I install `surface-ath10k-firmware-override` WiFi networks still don't appear.

**Comment by qzed** [comment]
Can you post a dmesg log?

**Comment by n8detar** [comment]
> Can you post a dmesg log?

[dmesg.txt](https://github.com/linux-surface/linux-surface/files/6512013/dmesg.txt)

**Comment by qzed** [comment]
Ah, looks like you're running a generic kernel. The override requires a patch that's only on the Surface kernels. Can you try booting with one of those?

**Comment by n8detar** [comment]
> Ah, looks like you're running a generic kernel. The override requires a patch that's only on the Surface kernels. Can you try booting with one of those?

The Surface Go doesn't require the surface kernel, should I still install it?

**Comment by qzed** [comment]
Yes. While all (other) things should normally work on the Go without special kernels, the workaround itself requires a [patch](https://github.com/linux-surface/kernel/commit/19d746dc9980d9109b93c9424138d3966c8a67cf) that is not upstream (and since it's a workaround, probably never will be). I know that's a bit unfortunate, sorry.

So for now your options are replacing / removing board files manually or installing a Surface kernel and trying the workaround via the package.

**Comment by n8detar** [comment]
OK, installing surface kernel now.

**Comment by n8detar** [comment]
With both the surface kernel and `surface-ath10k-firmware-override` installed WiFi is working as expected.

**Comment by qzed** [comment]
Awesome, thanks for testing!

**Comment by qzed** [comment]
Btw. for people wanting to go with the manual override, the board file is now also available in the repository of that package. I'll upate the links in the wiki now.

**Comment by qzed** [comment]
It seems that the `K1535_Debian/board.bin` is not actually the correct file. see #542.
