### ISSUE TITLE
Errror invalid signature, you need to load the kernel first

### ISSUE THREAD

**Issue by benonymus** [linux-surface/linux-surface#450]
Hey

I am trying to switch to this kernel on ubuntu on a surface laptop go, but when I boot and select ubuntu I am getting the following error:

error: /boot/vmlinuz-5.12.6-surface has invalid signature.
error: you need to load the kernel first

I was following the step by step guide, but I was never asked for the `surface` password.

Should I have selected enroll mok instead of continue boot?

What can I do form here?

I am able to boot back into the old kernel.

Thanks

**Comment by qzed** [comment]
> Should I have selected enroll mok instead of continue boot?

Yes, at this point you're trying to boot into the Surface kernel, which is signed by a key that you haven't enrolled. That is precisely what the error message tells you (invalid signature, meaning that the signature could not be validated, which is due to the key not being known).

> What can I do form here?

Boot into the standard Ubuntu kernel (which is signed by Ubuntu's key, which is already enrolled). With that, uninstall and then re-install the `linux-surface-secure boot-mok` package (don't just re-install, you really need to uninstall it first for the script to trigger). After that, reboot and, when asked, choose to enroll the MOK. There you should be asked for the password.

**Comment by benonymus** [comment]
Yes, that worked!

Thank you!
