### ISSUE TITLE
"unknown filesystem type 'xfs'" When attempting to boot linux surface kernel

### ISSUE THREAD

**Issue by kevindurb** [linux-surface/linux-surface#453]
Followed the guide for Arch Linux, after installing the linux surface kernel i added a config for booting the new kernel to my systemd-boot entries
```
title  Arch Linux Surface
linux  /vmlinuz-linux
initrd  /intel-ucode.img
initrd  /initramfs-linux-surface.img
options root="PARTUUID=<uuid for my drive>" rw
```
The only difference between this entry and the working mainstream linux one is the 4th line
When selecting this entry at boot i get `unknown filesystem type 'xfs'` and i get kicked to a prompt

### Environment

- Hardware model: Surface Pro 3
- Kernel version: `Linux tatooine 5.12.5-arch1-1 #1 SMP PREEMPT Wed, 19 May 2021 10:32:40 +0000 x86_64 GNU/Linux`
- Distribution: Arch Linux

Im using systemd-boot instead of grub and im not using secureboot yet

[dmesg.log](https://github.com/linux-surface/linux-surface/files/6556905/dmesg.log)

**Comment by kevindurb** [comment]
I guess i should also mention. My `/` partition is xfs

**Comment by qzed** [comment]
> Followed the guide for Arch Linux, after installing the linux surface kernel i added a config for booting the new kernel to my systemd-boot entries
> 
> ```
> title  Arch Linux Surface
> linux  /vmlinuz-linux
> initrd  /intel-ucode.img
> initrd  /initramfs-linux-surface.img
> options root="PARTUUID=<uuid for my drive>" rw
> ```

This looks like you're trying to boot the official Arch kernel (`vmlinuz-linux`) with the Surface kernel initramfs (`initramfs-linux-surface.img`). The second line should read `linux /vmlinuz-linux-surface`.

I assume what's happening is that it tries to load `vmlinuz-linux`, tries to load the XFS module from the initram (support is provided via modules and not built in, i.e. `CONFIG_FS_XFS=m`), and fails to do that because the kernel versions don't match (or rather the modules for that kernel version aren't provided in the initram). Due to that it doesn't have an XFS driver during boot and fails with the given message.

The Surface kernel config is based on the config of the official Arch kernel, so XFS should work out of the box.

**Comment by kevindurb** [comment]
:man_facepalming: omg thank you i feel embarased hahah It boots now! Thank you @qzed !!
