### ISSUE TITLE
Failed to open \EFI\BOOT\grub64.efi:

### ISSUE THREAD

**Issue by tharrisone** [linux-surface/linux-surface#504]
Some time after installing the surface-linux kernel I popped in a usb drive and noticed that it wouldn't boot. I have secure boot off because it won't boot Linux with it on for some reason. I've tried to boot various Linux OS's via usb drive got similar errors.

Here is my drive setup, which is stock and encrypted:

nvme0n1         259:0    0 119.2G  0 disk  
├─nvme0n1p1     259:1    0   498M  0 part  /boot/efi
├─nvme0n1p2     259:2    0     4G  0 part  /recovery
├─nvme0n1p3     259:3    0 110.8G  0 part  
│ └─cryptdata   253:0    0 110.7G  0 crypt 
│   └─data-root 253:1    0 110.7G  0 lvm   /
└─nvme0n1p4     259:4    0     4G  0 part  
  └─cryptswap   253:2    0     4G  0 crypt [SWAP]
My system info:
Surface Pro 6
Pop!_OS 21.04
Linux LEVIATHAN 5.12.14-surface #1 SMP Fri Jul 2 17:30:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by qzed** [comment]
> I have secure boot off because it won't boot Linux with it on for some reason.

That really depends on the distribution you use, or rather whether the bootloader is signed or not (and also what you've selected for the secure-boot option). Some distributions (Fedora and Ubuntu at least) come with signed bootloaders, so they should boot if you've selected 3rd-party keys (they won't boot with MS-only keys). Other distros like Arch don't come with a signed bootloader, so you have to disable secureboot for installing and manually set up everything later.

> I've tried to boot various Linux OS's via usb drive got similar errors.

What exactly did you do and where did you get the error? This sounds like it's some pre-bootloader issue and you might have misconfigured the EFI boot entries. What happens if you explicitly boot from USB by selecting that in the UEFI menu (slide that entry to the left to immediately boot IIRC)?

**Comment by tharrisone** [comment]
Actually it was my fault because I didn't follow the last step on your github wiki that would install the signed certs. After I did that I got the mokmanager screen and registered the cert all my usb sticks booted and I had all the files that were necessary in my /boot/efi. I will close this one and thanks a lot for making my surface pro 6 usable :D.
