### ISSUE TITLE
CONFIG_X86_5LEVEL: an unnecessary memory hog?

### ISSUE THREAD

**Issue by yatli** [linux-surface/linux-surface#541]
The released kernels are compiled with 5-level page table.
The behavior is specified in some config files, for example here: https://github.com/linux-surface/linux-surface/blob/64187798fc18bfc023f931ec38dc3b019cb49dc8/pkg/arch/kernel/config#L446

A quick search of CONFIG_X86_5LEVEL does not hit a Ubuntu config file, but I can confirm that `CONFIG_X86_5LEVEL` is in `/boot/config-5.13.7-surface`.

It's probably a good idea to disable this because a 5-level page table is there for super large systems and introduces huge memory overhead + PF penalty even with a hardware walker. The default one is good enough for surface models, 

Disabling it leads to significantly lower memory consumption -- I initially noticed it because running GNOME3+Firefox and nothing else, a few tabs, will eat all 16GB of memory pretty soon and I was thinking of memory leaks :)

**Comment by qzed** [comment]
> The default one is good enough for surface models,

This is the default of the respective distributions. We did not explicitly enable this, it comes from the base configs we use, which we take from those distributions (the one you've linked is the one we've copied from Arch).

> introduces huge memory overhead + PF penalty even with a hardware walker

I can see the issue with a higher page-fault penalty (one additional physical memory access in the worst case), but I don't believe this should create a huge memory overhead. I believe all that's needed in terms of memory is space for the level 5 list. Do you have some statistics/source on that?

> Disabling it leads to significantly lower memory consumption -- I initially noticed it because running GNOME3+Firefox and nothing else, a few tabs, will eat all 16GB of memory pretty soon and I was thinking of memory leaks :)

Did you actually test this properly? An additional page table level should not lead to _that_ much more memory usage. I believe that should, at most, be in the lower megabytes.

Unless there are some serious issues, I'd prefer sticking to the distro configs as far as possible. While I see the appeal of tuning the kernel config for Surface devices specifically, using the distro defaults ensures that those options are well tested and we're less likely to run into any obscure problems.

**Comment by yatli** [comment]
Thanks for the quick response.
No proper testing, sorry about that -- early days hacking with a SP5 resurrected from an enterprisy-too-actively-protected-idle-to-thermal-cap-almost-a-paperweight windows 10 installation, and this kernel is a bless!

I also don't have references about the memory consumption other than https://en.wikipedia.org/wiki/Intel_5-level_paging -- but it aligns with my intuitions -- 5-level table would be fine if the addresses are compact, but if the distro also enables an address randomizer it will be scattered all over the place, and upscale memory consumption considerably -- multiplied by the number of processes -- and the current sandbox-based browsers have a lot of them.

> This is the default of the respective distributions. 

I do think it's a good idea to stick with the distro defaults since the whole user space may be configured around that, but:
```
yatli@YATAO-SP:~$ grep CONFIG_X86_5LEVEL /boot/config-5.13.7-surface 
CONFIG_X86_5LEVEL=y
yatli@YATAO-SP:~$ grep CONFIG_X86_5LEVEL /boot/config-5.4.0-81-generic 
# CONFIG_X86_5LEVEL is not set
```

There isn't a complete config file for Ubuntu so what I did is to compare the configs of official 5.4 vs. the linux-surface binary release manually. This is one of the more interesting differences.

**Comment by qzed** [comment]
Not sure how up-to-date this is: https://lwn.net/Articles/717300/. By default, memory should only be allocated in 47-bit addresses, so only in the 4-level space if I understand that correctly. So if the application isn't specifically requesting memory in high areas, it should not make a difference (I assume that randomization also obeys this). `/proc/meminfo` should show some stats on that. The `PageTables` entry should at least give a hint on what's being used. It's described as "amount of memory dedicated to the lowest level of page tables" so if ASLR kicks in it should be noticeable there, I think.

Seems like it isn't enabled for 5.4 yet, but the current 21.04 / 5.11 kernel config has that enabled (see config file in https://packages.ubuntu.com/hirsute/linux-headers-5.11.0-31-generic). We take (or rather build) our Ubuntu configs directly from the Ubuntu mainline repo (https://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack), so there may be some differences to standard Ubuntu configs because we (and the mainline repo) are usually quite a bit ahead in kernel versions (and mainline configs also seem to differ slightly). If you spot any significant differences to the latest distro kernel, let us know.

**Comment by yatli** [comment]
I did a quick and dirty test:

1. Reboot to linux-surface 5.13.7
2. Login to GNOME3, launch firefox, launch nautilus, launch gnome-terminal
3. Go through all the remembered tabs to wake them up
4. cat /proc/meminfo ~/surface.meminfo
5. Reboot to yk 5.13.12
6. Login to GNOME3, launch firefox, launch nautilus, launch gnome-terminal
7. Go through all the remembered tabs to wake them up
8. cat /proc/meminfo ~/yk.meminfo

It aligns with my previous experiences with memory consumption. Not in particular with `PageTables` (a few megs, but "lowest" you mentioned means LSBs of the address?), but the total difference is significant.

I'm attaching the two meminfo cats here:
[meminfo.zip](https://github.com/linux-surface/linux-surface/files/7034134/meminfo.zip)

**Comment by qzed** [comment]
> "lowest" you mentioned means LSBs of the address?

I believe that should be memory consumption of the lowest level of tables, so yeah, tables responsible for LSBs.

> that should not be too different because it correlates only to the nr. of allocated pages), but the total difference is significant.

That should depend a) on the number of allocated pages and b) in what space they have been allocated: If the same number of pages has been allocated, but is spread across all available space, this number should be (in general) larger than if the pages have all been allocated on the same upper address.

Or in other words: For a new page table level to cause higher memory consumption, pages must be spread across that table (and not just collected below a single entry). And if they are spread across that (higher-level) table, they cannot share the lower level tables, so that number must go up.

Further that number should provide an estimate on the memory consumed by the upper level tables (since it's a tree structure), so total memory consumption by page tables should be something along the lines of `mem_lowest_level + mem_lowest_level / n + mem_lowest_level / n^2 + ... + mem_lowest_level / n^4` (assuming it's balanced), where `n` is the number of entries per table. Worst case that turns into `5 * mem_lowest_level`, which would be ~250MB in your case (vs ~200MB with level 4 pages). So I'm not sure we can explain that with level 5 tables.

**Comment by yatli** [comment]
Thanks for the explanation! makes sense to me to think of it as a uniform balanced tree. Could be unbalanced and more fragmented depending on the workload and `malloc` implementations, but the idea is the same.

So the problem may be laying somewhere else, eating an extra gigabyte with similar workload.

I need to do more testing.

**Comment by yatli** [comment]
I think I figured this out. `slabtop` reveals that ZFS is doing a lot of stuff behind the scene, and it does not count as conventional "cache".
Guess it's just me getting outdated in 2021 :D
Thanks again!
