### ISSUE TITLE
LVM Encrypted OS doesn't allow typing with onboard keyboard

### ISSUE THREAD

**Issue by DrBrad** [linux-surface/linux-surface#592]
I have no idea if this would be considered a linux-surface bug or an Ubuntu bug. However you still need an external keyboard if you are using Ubuntu with LVM encryption. Once you have correctly typed the LVM password you may then unplug the external keyboard and use the laptop as normal.

### Environment

- Hardware model: Surface Laptop 4 (AMD)
- Kernel version: v5.14.9-surface
- Distribution: Ubuntu 20.04

**Comment by qzed** [comment]
The problem is probably that you don't have the necessary kernel modules available when the LVM password prompt runs.

The way this usually works is that the kernel and initramfs (initram, initrd, initial ramdisk, whatever you prefer) are stored unencrypted or are being decrypted by the bootloader, e.g. GRUB if you've got an encrypted boot partition. When GRUB/your bootloader runs, UEFI provides the drivers via its pre-boot environment (IIRC, might get the terms wrong/mixed up). So at that point you should still be able to use the keyboard/touchpad thanks to UEFI.

This changes once you boot into the kernel though. At that point the device switches out of the pre-boot environment and with it all UEFI provided drivers are gone. Now if you encrypt your root partition (or if the file-system is not built into the kernel), the kernel does not have access to the root partition. Instead it loads the initial ramdisk / initramfs from the (now) unencrypted initram file. This file is expected to contain all driver modules (and firmware and config files) that the kernel needs during boot, but are not built into the kernel. So to say, the initramfs contains a minimal viable system.

In your case in particular, this means that the kernel is booted and has loaded the initramfs and now asks you to unlock the root partition. However, since the necessary drivers for the keyboard are not included in the initramfs, that doesn't work. The solution is to include those drivers into the initramfs. I'm not entirely sure how that's done on Ubuntu, but http://manpages.ubuntu.com/manpages/trusty/man5/initramfs.conf.5.html should help get you started.

The modules you'll need to include are listed at https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-3#using-the-built-in-keyboard-with-disk-encryption, but I'm not sure if that list is up to date/exhaustive for the AMD models.

**Comment by DrBrad** [comment]
I realized that I wrote the wrong version, I have a Surface Laptop 4 (AMD) not a Surface Laptop 3 (AMD).
Are the listed modules the same as what will be needed for the 4?

**Comment by qzed** [comment]
> Are the listed modules the same as what will be needed for the 4?

Yeah, should be the same for all AMD models, regardless of generation.

**Comment by DrBrad** [comment]
Awesome, I appreciate all your help!

This was the process:
Type:
`sudo gedit /etc/initramfs-tools/modules`

Add these lines:
```
surface_aggregator
surface_aggregator_registry
surface_hid_core
surface_hid
pinctrl_amd
8250_dw
```
Save

Type:
`sudo update-initramfs -u`

Reboot!
