### ISSUE TITLE
[SB3] Request for Testing: KIP Subsystem on Surface Book 3

### ISSUE THREAD

**Issue by qzed** [linux-surface/linux-surface#621]
Hi all,

the new Surface Pro 8 (and Surface Pro X) use a dedicated subsystem ("KIP") for handling the detachable keyboard cover. On the Surface Book 3, the current implementation for handling the detachable Surface System Aggregator Module (SSAM) client devices contained in the base uses the DTX subsystem.

That means that, right now, we have two device hubs in the kernel code which do essentially the same. I believe that the DTX subsystem, while the it also lets us know when the base has been detached, may be exclusively intended for controlling the locking mechanism and handling the detachment request-button, and that the Surface Book 3 might also be using the KIP subsystem for actual device management (i.e. connected/disconnected notifications).

If it turns out that the KIP subsystem provides events for device detachment/re-attachment, we can save a bit of code and unify those parts with the Surface Pro 8, hopefully making things a bit more stable and easier to maintain.

To help test this, you can follow these steps:
1. Clone the Surface Aggregator Module repository and change into it:
   ```
   git clone https://github.com/linux-surface/surface-aggregator-module.git
   cd surface-aggregator-module
   ```
2. Load the debug interface for the Surface Aggregator Module:
    ```
    sudo modprobe surface_aggregator_cdev
    ```
3. Enable events of the KIP subsystem:
   ```
   sudo ./scripts/ssam/events.py enable 0x01 0x01 0x0b 0x0c 0x0e 0x00 0x01
   ```
   If that command fails, you don't need to continue.
4. Start listening to incoming KIP subsystem events:
   ```
   sudo ./scripts/ssam/events.py listen 0x0e
   ```
   Note: This command will run and log events until you terminate it with `ctrl-c`. Please keep it running for the next steps.
5. Detach the tablet from the base, wait a bit and re-attach it. Preferably do this twice or so and also re-attach it in reverse (i.e. studio/canvas mode). If there are any events emitted, please post them here.

During this, you should also have a look at the dmesg log, e.g. via `sudo dmesg -w` in a separate terminal and check if there are any errors.

CC @shieldwed, @NickyTope

**Comment by Unknown-Fllooo** [comment]
I would love to help, but when I try to execute "sudo modprobe surface_aggregator_cdev" it won't find the module.

**Comment by qzed** [comment]
@Unknown-Fllooo what kernel version are you on? This should work on the latest Surface kernels and also the latest Arch distro kernels.

**Comment by Unknown-Fllooo** [comment]
> @Unknown-Fllooo what kernel version are you on? This should work on the latest Surface kernels and also the latest Arch distro kernels.

Oh, I just realized I didn't upgrade my kernel to the latest version, I'm still on 5.14.8a.

**Comment by qzed** [comment]
It should work on all v5.14 kernels. Maybe you made a typo?

**Comment by Unknown-Fllooo** [comment]
> It should work on all v5.14 kernels. Maybe you made a typo?

I had to fix some things, my surface kernel had some issues, probably because i over modded it a little much.
Here is the output from step 4:
`Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[04] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[04] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[00] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
Event { tc=0e, tid=01, cid=2c, iid=00, data=[01] }
Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
`

**Comment by qzed** [comment]
Perfect, thanks!

So it seems like this worked and you:
1. Detached the tablet.
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
   ```
2. Re-attached it in "laptop mode".
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
   ```
3. Detached it again.
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
   ```
4. Re-attached it again in "laptop mode".
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
   ```
5. Detached it again.
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
   ```
6. Attached it in "canvas mode"
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[04] }
   ```
7. Detached it yet again.
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
   ```
8. Attached it in "laptop mode".
   ```
   Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
   ```

Is this correct?

**Comment by Unknown-Fllooo** [comment]
> Perfect, thanks!
> 
> So it seems like this worked and you:
> 
> 1. Detached the tablet.
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
>    ```
> 2. Re-attached it in "laptop mode".
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
>    ```
> 3. Detached it again.
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
>    ```
> 4. Re-attached it again in "laptop mode".
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
>    ```
> 5. Detached it again.
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
>    ```
> 6. Attached it in "canvas mode"
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[04] }
>    ```
> 7. Detached it yet again.
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[01] }
>    ```
> 8. Attached it in "laptop mode".
>    ```
>    Event { tc=0e, tid=01, cid=1d, iid=00, data=[03] }
>    ```
> 
> Is this correct?

Yes, it totally is, if you need help with any other testing. Just message me or mention me. :)

**Comment by qzed** [comment]
Perfect, thanks! That's it for now.
