### ISSUE TITLE
Monitor mode on SP6

### ISSUE THREAD

**Issue by midozalouk** [linux-surface/linux-surface#680]
Hello sir
is monitor mode supported on Marvell wifi card in surface devices (SP6)
the output of airmon is the following

Driver[Stack]-FirmwareRev               Chipset                                                                         Extended Info

mwifiex_pcie[mac80211]-unavailable      Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless               mode managed

if it isn't supported can you tell me how to add support to it 

thanks

**Comment by jonas2515** [comment]
The mwifiex driver doesn't support monitor mode (see missing NL80211_IFTYPE_MONITOR [here](https://elixir.bootlin.com/linux/v5.16.3/source/drivers/net/wireless/marvell/mwifiex/cfg80211.c#L4359).

It's not that easy to add support for that, most likely it's impossible since mwifiex is a fullmac driver that implements most functionality in proprietary firmware running on the card. Afaik the mwlwifi (softmac) driver has its own firmware and supports monitor mode. Unfortunately it's not upstreamed, not maintained for our card and also not exactly in a working state.

**Comment by midozalouk** [comment]
Hello @jonas2515 
thanks for your replay
sorry if i have a little experience  in networking .
if you can help me understand the difference between softmac and fullmac ????


if have found another driver the still has support

mwl8k 

https://wireless.wiki.kernel.org/en/users/drivers/mwl8k

can you please guide me how to implent it

**Comment by midozalouk** [comment]
Any help sir ?

**Comment by jonas2515** [comment]
First of all I have never looked at the mwl8k driver, so there I'm just as clueless as you. For mwifiex, from what I can see it's simply impossible to implement monitor mode, as there is no firmware support.

So no I can't really help you. If you have lots and lots of time and you're looking to learn how wifi works, take a look at the mwlwifi code (a softmac driver that has partial support for our card), and then implement monitor mode there, but this is definitely not a beginner task.
