### ISSUE TITLE
How to install for android x86

### ISSUE THREAD

**Issue by snnbyyds** [linux-surface/linux-surface#757]
[Description of the bug or feature]

### Environment

- Hardware model: 
- Kernel version: 
- Distribution: 

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by yatli** [comment]
best bet is to start from a well supported distro and run containerized android.

check this out: https://waydro.id/

**Comment by mainmachine** [comment]
I managed to get Android x86 installed on my Surface 3 (non Pro) and I do not recommend it. While the UI works great, sleep did not, but the biggest issue is that most apps just flat out do not work. F-droid worked great, and lots of utility-type apps worked great, but of course only if there's an x86 version of it available.

My use case is a tablet for media consumption and portability, and for this Android x86 is a terrible choice. If your use case is just simple utilities, email or other non-video or audio apps, then Android x86 might be a good choice, but if that's the case then any Linux distro will do the same but with far fewer problems and more control.

**Comment by mainmachine** [comment]
> best bet is to start from a well supported distro and run containerized android.
> 
> check this out: https://waydro.id/

[Anbox](https://anbox.io/) works great for me on my desktop system - how does this compare...?

**Comment by yatli** [comment]
AFAIK:

- Both uses binder and ashmem kernel modules for Android-y things
- Waydroid is container-based.
- Anbox runs on X11, Waydroid runs on Wayland. Might be good or bad for you depending on your hardware configuration (in particular, NVIDIA).

**Comment by hmtheboy154** [comment]
we on BlissOS have surface builds

**Comment by rommeswi** [comment]
@hmtheboy154 and others: I am wondering how to build the linux-surface kernel with the android settings required by waydroid. The waydroid instructions for changing the config file are clear and simple but the config in linux-surface/pkg/arch/kernel says "# Automatically generated file; DO NOT EDIT." Should I instead place the kernel adjustments into linux-surface/configs/surface-6.6.config ?

**Comment by qzed** [comment]
Depends on the distro. We've [enabled binder for Ubuntu/Debian](https://github.com/linux-surface/linux-surface/blob/c58cae4193e8007cb1d8a548db759bcdc3ce5c24/pkg/debian/kernel/ubuntu.config#L46-L51) because Ubuntu has it enabled. For other distros, you might need to add  yourself.

> Should I instead place the kernel adjustments into linux-surface/configs/surface-6.6.config

In reality, you can add it pretty much anywhere, really. The config starting with `# Automatically generated file; DO NOT EDIT` is the base config, which we copied from Arch. If you're somewhat careful, you can edit it because we run it through the kernel's config script anyways (just make sure that you don't have conflicting options). However, if you want to do it properly, you should add it to [pkg/arch/kernel/arch.config](https://github.com/linux-surface/linux-surface/blob/c58cae4193e8007cb1d8a548db759bcdc3ce5c24/pkg/arch/kernel/arch.config). But you can also add it to the configs in `configs/`. In the end, all of those configs get merged, so it doesn't really matter that much.
