### ISSUE TITLE
kdump not working on surface kernels

### ISSUE THREAD

**Issue by ishland** [linux-surface/linux-surface#769]
[Description of the bug or feature]

### Environment

- Hardware model: Surface Pro 5
- Kernel version: `5.16.13-surface`
- Distribution: Debian 11

### Description

Kernel crash dump does not work. A kernel crash is occurred inside the crashkernel environment when manually triggering a crash. 
Kernels shipped with debian itself (`5.10.0-12-amd64`) works.

**Comment by qzed** [comment]
Do you happen to know the kernel config options required for that? It may be possible that we can't support this due to the limitations of GitHub Actions. In particular, we have to disable debug info as (IIRC) we may otherwise run out of disk space.

**Comment by ishland** [comment]
This is what I found in kernel docs: https://www.kernel.org/doc/Documentation/kdump/kdump.txt

Also the screen content is broken when the kdump kernel crashes. 
This is what I see: (copied by hand)
```
ipu3-cio2 0000:00:14.3: DMA output error: 0x7ffff
ipu3-cio2 0000:00:14.3: DMA output error on CSI2 buses: 0xf
ipu3-cio2 0000:00:14.3: unknown interrupt 0xf0f80000 on DE
BUG: kernel NULL pointer dereference, address: 0000000000000d20
#PF: supervisor read access in kernel mode
**content corrupted**
PGD 0 P4D 0
Oops: 0000 [#1] PREEMPT SMP PTI
CPU: 0 PID: 38 Comm: kswapd0 Tainted: G WC 5.16.13-surface #1
Hardware name: Microsoft Corporation Surface Pro/Surface Pro. BIOS 235.3732.768 04.20.2021
RIP: 0010:cio2_irq+0x130/0x410 [ipu3_cio2]
...more
```

**Comment by qzed** [comment]
So from that document, we have most of the options that seem to be required, in particular:
```
CONFIG_KEXEC=y
CONFIG_SYSFS=y
CONFIG_CRASH_DUMP=y
CONFIG_PROC_VMCORE=y
CONFIG_RELOCATABLE=y
```

Options that are different are:
```
CONFIG_DEBUG_INFO=n
CONFIG_SMP=y
```

As I've mentioned above, we unfortunately can't enable `CONFIG_DEBUG_INFO` due to build limitations. For `CONFIG_SMP` there is apparently a workaround with a kernel command line option. This is definitely not an option that we would want to change for non-debug kernels due to the performance loss inherent when disabling SMP (and I doubt the original Ubuntu kernel disables that).

So if it really is the missing `CONFIG_DEBUG_INFO`, then I'm sorry but it's not feasible for us to support this (as much as I'd love to have debug symbols for better debugging...).

**Comment by ishland** [comment]
Fixed by adding `module_blacklist=ipu3_cio2,ipu3_imgu` to `KDUMP_CMDLINE_APPEND`. Might worth adding this to the wiki.

**Comment by qzed** [comment]
Hmm interesting. CC @djrscally, although I'm not sure what can be done about that or why those modules cause issues.

**Comment by djrscally** [comment]
Thanks @qzed 

I'm not familiar with kdump; what is that exactly?
