### ISSUE TITLE
Surface Laptop Studio | Fedora 36 Sensors Works Out of The Box

### ISSUE THREAD

**Issue by m1nicrusher** [linux-surface/linux-surface#830]
I just installed Fedora 36 with kernel 5.17.5 from fresh installation. The auto brightness sensor and CPU temperature sensors works perfectly out of the box. Any other mate has same experience? I'm guessing we could update the feature matrix for SLS if most of the users are experiencing the same.

### Environment

- Hardware model: Surface Laptop Studio
- Kernel version: 5.17.5-300.fc36.x86_64 / 5.17.8-300.fc36.x86_64
- Distribution: Fedora 36

**Comment by NP-chaonay** [comment]
[m1nicrusher](https://github.com/m1nicrusher)

Sensors for SLS also include
- Screen Rotation: on my Ubuntu 22.04 LTS GNOME is not work out of box but the script given in this GitHuB repo seem to (breif test) detect sensors and read correctly.
- Tablet mode sensors: I think it work but has not tested by me, but Ubuntu 22.04 LTS GNOME doesn't work with that.

Have you try all above, if yes then I think it is good to change to / instead of ?

**Comment by NP-chaonay** [comment]
I have tested , cpu/nvme temperature sensor works and else works and I have updated the matrix.

you could safely close this.
