### ISSUE TITLE
Surface Laptop Go 2 is missing in documentation

### ISSUE THREAD

**Issue by mbrennwa** [linux-surface/linux-surface#855]
As the title says, the new Surface Laptop Go 2 is not covered in the documentation (and in the feature matrix). Would be useful to include the SLG2.

**Comment by qzed** [comment]
We're also missing an acpidump for that. I haven't heard any reports of it yet (might be too early), so I can't say much about it. If it's similar to the SLG1, we'll at least need the usual small patch for battery and platform profile support.

**Comment by mbrennwa** [comment]
Sure. It would be useful to add these unknowns to the docs so that people are not left in the dark about this. Consider someone thinking about getting a new SLG with the intention of running Linux on it. Will the SLG2 work with Linux? Or would it be better to get a SLG1 for now to be on the safe side with Linux? With a bit of background in your docs it would be an easy decision.

**Comment by qzed** [comment]
I've added a column in the feature matrix so that it's easier to enter that information and I've added the SLG2 to a new "Unknown" list. I had hoped that devices not being present on the wiki would be understood as "we don't know anything about this device", but I can see that this could be somewhat confusing with an entry for the SLG (1) being present, or that people could assume that "normally keyboards or battery status works out of the box". I do hope that the feature-matrix entry with the question marks makes it clear that we don't know whether keyboard or battery status will work.

Apart from that, I'm somewhat hesitant to write down anything else as that'd be, at this point, only speculation. And I don't want to set any expectations. Maybe there should be a more general page along the lines of "things that might not work out-of-the-box on new devices and why". I'm open for more ideas, if you have any.

**Comment by mbrennwa** [comment]
I feel the docs are fine as they are now.

**Comment by nickdepinet** [comment]
@qzed - I've got an SLG and SLG2 - what info would you like off the device? Just an acpidump?

**Comment by qzed** [comment]
[`./scripts/diagnostics.sh full`](https://github.com/linux-surface/linux-surface/blob/master/scripts/diagnostics.sh) would be great! That collects an acpidump and some system information (lspci, lsusb, ...).

**Comment by nickdepinet** [comment]
> [`./scripts/diagnostics.sh full`](https://github.com/linux-surface/linux-surface/blob/master/scripts/diagnostics.sh) would be 
great! That collects an acpidump and some system information (lspci, lsusb, ...).

Output attached:
[diagnostics.tar.gz](https://github.com/linux-surface/linux-surface/files/9059851/diagnostics.tar.gz)

**Comment by qzed** [comment]
Thanks! So it looks like touch/pen is handled via USB. Does that work out-of-the-box? Webcams are also USB, so should also work out-of-the-box, I guess. Could you also update the feature matrix at https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#surface-laptops?

And are there any things missing, e.g. Keyboard/touchpad or battery? It does seem to use SAM and there's a new `MSHW0290` WSID device ID which we likely need to add support for.

**Comment by nickdepinet** [comment]
Ok, I've updated the feature matrix with the working stuff. Performance modes and battery status don't appear to be working on ubuntu 22.04 w/5.18.9-surface kernel. I've attempted to build surface-aggregator-module with the MSHW0290 modeling after the slg1 bits plus the two changes to get it to build- [nickdepinet/surface-aggregator-module@47f9dcf](https://github.com/nickdepinet/surface-aggregator-module/commit/47f9dcfab97f39f42f01f14646a8b14512256669), but I can't seem to get battery status working (nothing in gnome, no batteries showing up in /sys/class/power_supply)

**Comment by qzed** [comment]
Ah, I need to update that module... it's a bit out of date. Can you try and run
```
modprobe surface_aggregator_cdev
./scripts/ssam/ctrl.py request 0x02 0x01 0x01 0x01 0x01
./scripts/ssam/ctrl.py request 0x02 0x01 0x02 0x01 0x01
./scripts/ssam/ctrl.py request 0x02 0x01 0x03 0x01 0x01
```

That runs the standard battery functions and should hopefully return some data if the interface hasn't changed.

**Comment by nickdepinet** [comment]
> Ah, I need to update that module... it's a bit out of date. Can you try and run
> 
> ```
> modprobe surface_aggregator_cdev
> ./scripts/ssam/ctrl.py request 0x02 0x01 0x01 0x01 0x01
> ./scripts/ssam/ctrl.py request 0x02 0x01 0x02 0x01 0x01
> ./scripts/ssam/ctrl.py request 0x02 0x01 0x03 0x01 0x01
> ```
> 
> That runs the standard battery functions and should hopefully return some data if the interface hasn't changed.

```
root@nick-slg2:/home/nick/surface-aggregator-module# modprobe surface_aggregator_cdev
root@nick-slg2:/home/nick/surface-aggregator-module# ./scripts/ssam/ctrl.py request 0x02 0x01 0x01 0x01 0x01
1f 00 00 00
root@nick-slg2:/home/nick/surface-aggregator-module# ./scripts/ssam/ctrl.py request 0x02 0x01 0x02 0x01 0x01
00 00 00 00 00 14 9b 00 00 c8 a0 00 00 01 00 00 00 9c 1d 00 00 00 00 00 00 00 00 00 00 04 00 00 00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 00 e8 03 00 00 0a 00 00 00 0a 00 00 00 31 31 38 37 30 38 37 30 30 34 00 00 00 00 00 00 00 00 00 00 00 30 31 38 35 33 34 37 32 30 35 00 4c 49 4f 4e 00 53 4d 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
root@nick-slg2:/home/nick/surface-aggregator-module# ./scripts/ssam/ctrl.py request 0x02 0x01 0x03 0x01 0x01
01 00 00 00 9f 16 00 00 82 9b 00 00 1f 21 00 00
```

**Comment by NP-chaonay** [comment]
> > @nickdepinet New kernels should be available in the repo, can you give those a try?
> 
> battery functionality and performance modes working with the new kernel. I've updated the feature-matrix, but I'd say the SLG2 is fully usable with linux-surface 5.18.10

for S0ix testing you can use script from [this](https://github.com/intel/S0ixSelftestTool): these 3 below must be passed (these below  must shown green message):
- **s0ix suspend**: PC10 must be highest and enough which will be reported as green message
- **s0ix runtime when screen on**: doing this test when PC is idle only, and this test require screen to turn on about 1min so set screen timeout to higher first, PC8 must be highest and enough which will be reported as green message.
- **s0ix runtime when screen off**: same as above but PC10 should be highest instead, and screen timeout is not required.

If only s0ix runtime test failed, pls check process that runnning in background. 
For failed, it will display in red. For good condition result, it will be green.

**Comment by qzed** [comment]
I'm reopening this for S0Ix testing, but if that's a problem we should move this to a new issue.

**Comment by qzed** [comment]
@nickdepinet Thanks for testing!

**Comment by NP-chaonay** [comment]
> Need help interpreting these results, seems like a pass? @NP-chaonay

look similar to my result

s0ix suspend: works
s0ix scr off: PC10 state % available with message "not enough %"
s0ix scr on: PC8 state % available but not PC10 (that seem to be noted in intel s0ix how to acheive s0ix page on 01.org)

but your system do better on s0ix scr on testing, because SLG2 can acheive PC10 while screen is on.
so maybe s0ix on your system is properly working (I think it is safe to igore not enough notice and interpret it as green message like one of "PC10 is not acheive but PC8" message, since case of PC8-acheive-but-not-PC10, it shown green message, so your PC10+PC8 indicate that your system is better than only-PC8-state.) 

conclude: your s0ix is all success tested like my SLS, if someone said it failed then my is failed too.

**Comment by qzed** [comment]
I'm by far no expert on s0ix but things look good.
