### ISSUE TITLE
SP8 - Screen flickering [Ubuntu 22.04]

### ISSUE THREAD

**Issue by zed-wong** [linux-surface/linux-surface#881]
> > You might be just a ‘grub-update‘ away.
> 
> Nope, already done that multiple times. Maybe people more familiar with ubuntu can help. Thanks a lot!

I'm facing the same issue. `grub-update` didn't work.

_Originally posted by @zed-wong in https://github.com/linux-surface/linux-surface/issues/862#issuecomment-1198378195_

**Comment by zed-wong** [comment]
Environment

OS: Ubuntu 22.04 LTS x86_64
Hardware model: Surface Pro 8
Kernel: 5.18.12-surface

**Comment by zed-wong** [comment]
I finally figured it out. Instead of flickering, it's actually controlling the brightness based on its sensor. Haha.

**Comment by Irlee** [comment]
I have the same problem with my surface pro 7, how did you solve it?

**Comment by zed-wong** [comment]
> I have the same problem with my surface pro 7, how did you solve it?

Try this. https://github.com/linux-surface/linux-surface/issues/862#issuecomment-1234634343

**Comment by Irlee** [comment]
I think it may cased by PSR, however, this problem also occurs in Windows11（SP7) . When I updated the intel Iris Plus Graphics driver, the situation still didn't improve. I uninstalled ubuntu22.04 for SP7, because I will not use dual systems for a while in the future. This problem still occurs sometimes, but it's not as obvious. I'm starting to suspect that there might be a hardware problem. After that I downloaded WSL of ubuntu22.04 in microsoft store. Everything goes well.&nbsp;




lyh
***@***.***
