### ISSUE TITLE
Surface Book: Tablet Mode not activated when display attached reversly

### ISSUE THREAD

**Issue by OliverUrbann** [linux-surface/linux-surface#918]
With a Surface Book, you can insert the display the other way around so that it is not facing the keyboard. This way keyboard and touchpad are disabled but using my Ubuntu 22.04 and kernel 5.19.4-surface the Tablet Mode is not activated and so the OSK is not showing up and screen rotation is disabled. I think it is not a desired behaviour that both physical and virtual keyboard are disabled.

**Comment by qzed** [comment]
You have a SB1, right? That doesn't have a dedicated driver providing a tablet-mode switch yet, so I guess this behavior is to be expected. To implement something like this, the mechanism for detachment would need to be reverse engineered and someone would need to write a driver.

**Comment by OliverUrbann** [comment]
Yes, sorry, a SB1. I should have added that Tablet Mode is activated by detaching it from keyboard, so I guess the driver for other Surface Books works here, too. And on a SB2 Tablet Mode is also activated when attached reversely? Then probably there is a difference.

**Comment by qzed** [comment]
I know that the SB2 / SB3 driver isn't working here, because it runs via the EC which is different on the SB1 (and we don't have EC support for the latter).

I assume it's the heuristic of Gnome (or your desktop env), that kicks in when there's no actual tablet-mode switch detected. AFAIK this triggers when it detects/doesn't detect a keyboard, which explains why this is happening: Regardless of orientation, if the base is connected, the keyboard (IIRC running via USB) is also connected. It's only that it's disabled in reverse mode, but the USB device is still present and recognizable, so it still "exits" tablet mode.

**Comment by OliverUrbann** [comment]
Oh ok. Yes, using X11 it seems just touching the display activates it. Now on Ubuntu 22.04 and Wayland that's different. Thx! Then I think there is no quick solution.

**Comment by qzed** [comment]
Fwiw #93 is the relevant issue for SAM/EC on the SB1.

**Comment by NP-chaonay** [comment]
> disabled in reverse mode

let me clarify if I not wrong

SAM (Surface Controller HW chip) disable internal keyboard (if I not wrong base keyboard and base system also provided  by SAM), but the word "disable" is just prevent key press from sending data, so the kbd device is still existed. (why it must existed, I think it is technical limitation but not know reason)
