### ISSUE TITLE
Surface Laptop Studio - set the Touchscreen / Pen. I need help.Solved!!!!

### ISSUE THREAD

**Issue by Special-Niewbie** [linux-surface/linux-surface#961]
### SYSTEM

- Hardware model: `Surface Laptop Studio (Intel Core i7-11370H), NVIDIA GeForce RTX 3050 Ti, 32GB RAM , etc.`
- Kernel version: `6.0.1-surface`
- Distribution: `Ubuntu 22.04.1 LTS `
- Disk Encryption: `YES `
- Secure Boot: `YES `
- File System: `ext4/LVM`
- DKMS Installed: `DKMS`

Hello everyone,

not sure if I understood well about to activate the Touchscreen / Pen input on my SLS.

But the fact and my actual situation it's that in my SLS it doesn't work at all the Touchscreen or Pen input, please can you guide me what I should do to activate it? And on X11 it's working the Touchscreen/ Pen input? Or does only under Wayland Environment?

Thanks a lot for the help....

**Comment by fotnite-vevo** [comment]
Device-specific setup instructions can all be found linked on the feature matrix: https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#feature-matrix

I'm going to assume you got the touchpad functioning, since you didn't mention that.

For SLS you will need to install the ITHC driver from here to get the touchscreen working: https://github.com/quo/ithc-linux

You will also need the master branch version of the IPTSD kernel, instead of the one you installed when you followed the instructions to install the `linux-surface` kernel: https://github.com/linux-surface/iptsd

You will need to clone both of these repositories, install all of the dependencies listed on each of their front pages, and then follow the install instructions on each one. As I understand, you will need to reboot for IPTSD to start correctly. 

Also, X and Wayland will both work with these drivers, but you will probably have a much better experience with Wayland. Touch gestures for swiping to scroll with for the most part only work on Wayland, and multitouch gestures on both the touchscreen and touchpad are only natively supported if you use Wayland.

I don't think the `Notes` section on the ITHC install instructions apply to Ubuntu, but try out what they recommend if touchscreen still doesn't work after installing.

**Comment by Special-Niewbie** [comment]
> Device-specific setup instructions can all be found linked on the feature matrix: https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#feature-matrix
> 
> I'm going to assume you got the touchpad functioning, since you didn't mention that.
> 
> For SLS you will need to install the ITHC driver from here to get the touchscreen working: https://github.com/quo/ithc-linux
> 
> You will also need the master branch version of IPTSD, instead of the one you installed when you followed the instructions to install the `linux-surface` kernel: https://github.com/linux-surface/iptsd
> 
> You will need to clone both of these repositories, install all of the dependencies listed on each of their front pages, and then follow the install instructions on each one to install. As I understand, you will need to reboot for IPTSD to start correctly.
> 
> Also, X and Wayland will both work with these drivers, but you will probably have a much better experience with Wayland. Touch gestures for swiping to scroll with for the most part only work on Wayland, and multitouch gestures on both the touchscreen and touchpad are only natively supported if you use Wayland. You will have to change the touchpad configuration a bit if you decide to use Wayland, so that you can use the keyboard and touchpad when in tablet mode like how it functions on Windows. This can be found at the bottom of the same page you got the original touchpad instructions from: https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-Studio#touchpad-quirks
> 
> Note that you will need to use X if you want to use NVIDIA as your only GPU. Using only Intel or using hybrid mode should be fine on Wayland. If you want to use hybrid mode with Wayland, you will also need to force GDM to launch using Wayland. A guide on how to do that can be found here on the Arch Wiki (the instructions will work just as well on Ubuntu): https://wiki.archlinux.org/title/GDM#Wayland_and_the_proprietary_NVIDIA_driver And here on AskUbuntu (though the Arch Wiki entry is more descriptive): https://askubuntu.com/questions/1369250/how-do-i-enable-wayland-on-ubuntu-21-10-nvidia
> 
> I don't think the `Notes` section on the ITHC install instructions apply to Ubuntu, but try out what they recommend if touchscreen still doesn't work after installing.
> 
> I hope this outline is sufficient.

@fotnite-vevo , I don't know how to say THANK YOUUUUUU..... Everything it's fully works now.

Man, you really did my day, your guide was detailed and well instructed to me, I love when the people are clear to explain something.

About the TouchPad and the Keyboard at the Encrypted password stage, I already made the modifications with the help of other two DEVS of this project. I saw the other extra steps to do, but I wasn't sure if I need to do all of them. It tooks me some test to do , but after some trial I achieved all the results. 
All the steps from `ITHC` and `IPTSD` I followed and Installed into the system but even if I installed and reboot correctly, in the end to let it work everything it start only to work once I added in the following command:
`echo options ithc poll | sudo tee /etc/modprobe.d/ithc-poll.conf`

So, I confirm that on SLS-Ubuntu it works now everything included the PEN and touch screen, no errors it gived to me during the building processes of the new drivers to add into the kernel.

Finally, I can use the SLS as an Android Tablet with the Android apps thanks to **Waydroid** that I installed into the Linux System as well.
I don't know if someone will need the detailed steps to let it work, if yes , just ask here .... I will leave open another day this topic and then I will Close as solved !!!
