### ISSUE TITLE
404 on https://tmsp.io/fs/tmsp.asc (key used to sign Debian packages)

### ISSUE THREAD

**Issue by Quicksilver80** [linux-surface/linux-surface#98]
404 on https://tmsp.io/fs/tmsp.asc (key used to sign Debian packages)
https://github.com/linux-surface/linux-surface/wiki/Package-Repositories

**Comment by StollD** [comment]
I readded the key, but that will most likely not help you. The repos are unavailable right now because we are migrating them to a new setup under the linux-surface github organisation. They will soon be available again, under https://pkg.surfacelinux.com

In the meantime, you can download one of the releases for your distro from https://github.com/linux-surface/linux-surface - they are marked as tests but the packages should work just fine.

**Comment by andybiss** [comment]
Is there any update on the new repository and any keys for setup? None of the installation documentation references these changes.

**Comment by qzed** [comment]
Documentation will be updated after https://github.com/linux-surface/linux-surface/pull/86 lands. Should be soon(-ish).
