### ISSUE TITLE
[BUG][Arch Linux][SP6] Bluetooth Headset Microphone with HSP/HFP is not working.

### ISSUE THREAD

**Issue by farline99** [linux-surface/linux-surface#998]
### Environment

- Hardware model: Surface Pro 6
- Kernel version: 6.0.9-arch1-1-surface
- Distribution: Arch Linux, PipeWire, WirePlumber.

</details>

Hello, dear developers. While using Linux on my Surface I mentioned bug with my Bluetooth Headset Microphone. It was not working. After some hours of testing I understood that problem with Bluetooth built-in adapter drivers. Everything is ok with external bluetooth adapter plugged in USB Port. Problem is that I can't use HSP/HFP protocol with my headset, it does not give any output so and input. Everything is silent. Tried both with mSBC and CVSD. Tested headsets are Honor Earbuds 2 Lite and Marshall Mid. With external adapter CVSD variant is fully workable, microphone and output sound are there. What can I do? Maybe I have to install something else? I heard about some problems with Intel Bluetooth adapters on Linux)

**Comment by farline99** [comment]
Maybe some thoughts?)

**Comment by qzed** [comment]
Can confirm that HSP/HFP doesn't work on the SB2 as well... (no audio, no microphone) likely some problem with the Marvell WiFi/Bluetooth combo card since the Intel WiFi/Bluetooth combo card on my desktop works just fine. A2DP works (but naturally that doesn't provide microphone input). Both systems run Arch.

Also, it's not exclusive to the Surface kernel.

@jonas2515 maybe you have an idea?

**Comment by farline99** [comment]
Yeah, I think that problem is related to Marvell drivers for this card, but it is problem, some times very annoying)

**Comment by jonas2515** [comment]
Afaik HSP/HFP use a very different mode of bluetooth that's more of a constant stream of data instead of a packet based transmission, it has way lower latency but also no retries on failure and no checksums.

Since the wifi cards firmware just implements the standardized HCI via USB protocol when talking to the kernel and there's no special driver for it, I doubt there's anything we can do to fix issues with that mode. There's a bunch of quirks for bad behaving USB bluetooth devices [here](https://elixir.bootlin.com/linux/latest/source/drivers/bluetooth/btusb.c#L176), one could maybe play around with those a bit.

One thing that might also be interesting to check is whether it worked with older kernels, PulseAudio instead of pipewire, or also old BlueZ versions, sometimes the communication with the card subtly changes (especially between pulse and pipewire) and that might trigger bugs in the firmware.

**Comment by farline99** [comment]
Sad :(
